//////////////////////////////////////////////////////////////////////
// C++ source file generated by SpecC V2.2.1
// Design: susan_edge_detector
// File:   susan_edge_detector.cc
// Time:   Wed Oct 28 19:16:27 2015
//////////////////////////////////////////////////////////////////////

// Note: User-defined include files are inlined in this file.

// Note: System-defined include files are inlined in this file.

#include "susan_edge_detector.h"


unsigned int _IDcnt = 0;
// channel class definitions /////////////////////////////////////////

TLMHardwareBus::TLMHardwareBus()
    : _specc::channel()
{   /* nothing */
}

TLMHardwareBus::~TLMHardwareBus(void)
{   /* nothing */
}

#line 57 "./HWBus.sc"
void TLMHardwareBus::masterRead(bit<_BITLEN(15,0),true> a, bit<_BITLEN(31,0),true> *d)
{   
    A = a;
    _specc::notify(event(&rdy), ((void*)0));
    _specc::wait(event(&ack), ((void*)0));
     *d = ((bit<_BITLEN(31,0),true>)D);
    _specc::waitfor((39000));
}

#line 47 "./HWBus.sc"
void TLMHardwareBus::masterWrite(bit<_BITLEN(15,0),true> a, bit<_BITLEN(31,0),true> d)
{   

    A = a;
    D = d;
    _specc::notify(event(&rdy), ((void*)0));
    _specc::wait(event(&ack), ((void*)0));
    _specc::waitfor((34000));
}

#line 68 "./HWBus.sc"
void TLMHardwareBus::slaveRead(bit<_BITLEN(15,0),true> a, bit<_BITLEN(31,0),true> *d) {




    t1: _specc::wait(event(&rdy), ((void*)0));
    if (a != ((bit<_BITLEN(15,0),true>)A))
	goto t1;

     *d = ((bit<_BITLEN(31,0),true>)D);
    _specc::notify(event(&ack), ((void*)0));
}


void TLMHardwareBus::slaveWrite(bit<_BITLEN(15,0),true> a, bit<_BITLEN(31,0),true> d) {
    do  {
	_specc::wait(event(&rdy), ((void*)0));
    }
    while(

#line 85 "./HWBus.sc"
	a != ((bit<_BITLEN(15,0),true>)A));

    D = d;
    _specc::notify(event(&ack), ((void*)0));
}

#line 77 "susan_edge_detector.cc"
MasterHardwareSyncDetect::MasterHardwareSyncDetect(i_receive (&intr))
    : _specc::channel(), intr(intr)
{   /* nothing */
}

MasterHardwareSyncDetect::~MasterHardwareSyncDetect(void)
{   /* nothing */
}

#line 156 "./HWBus.sc"
void MasterHardwareSyncDetect::receive(void)
{   
    intr.receive();
}

#line 93 "susan_edge_detector.cc"
SlaveHardwareSyncGenerate::SlaveHardwareSyncGenerate(i_send (&intr))
    : _specc::channel(), intr(intr)
{   /* nothing */
}

SlaveHardwareSyncGenerate::~SlaveHardwareSyncGenerate(void)
{   /* nothing */
}

#line 165 "./HWBus.sc"
void SlaveHardwareSyncGenerate::send(void)
{   
    intr.send();
}

#line 109 "susan_edge_detector.cc"
MasterHardwareBusLinkAccess::MasterHardwareBusLinkAccess(IMasterHardwareBusProtocol (&protocol))
    : _specc::channel(), protocol(protocol)
{   /* nothing */
}

MasterHardwareBusLinkAccess::~MasterHardwareBusLinkAccess(void)
{   /* nothing */
}

#line 211 "./HWBus.sc"
void MasterHardwareBusLinkAccess::MasterRead(int addr, void *data, unsigned long int len)
{   
    unsigned long int i;
    unsigned char *p;
    bit<_BITLEN(31,0),true> word;

    for(p = (unsigned char *)data , i = 0; i < len; i++  , p++ )
    {   
	if ( !(i % 4u)) {
	    protocol.masterRead(addr,  &word);
	}

	 *p = ((unsigned char)((word(31,0, 31,24))).toInt());
	word = word << 8;
    }
}

#line 189 "./HWBus.sc"
void MasterHardwareBusLinkAccess::MasterWrite(int addr, const void *data, unsigned long int len)
{   
    unsigned long int i;
    unsigned char *p;
    bit<_BITLEN(31,0),true> word = bit<32,true>("00000000000000000000000000000000");

    for(p = (unsigned char *)data , i = 0; i < len; i++  , p++ )
    {   
	word = (word << 8) +  *p;

	if ( !((i + 1) % 4u)) {
	    protocol.masterWrite(addr, word);
	    word = 0;
	}
    }

    if (i % 4u) {
	word <<= 8 * (4u - (i % 4u));
	protocol.masterWrite(addr, word);
    }
}

#line 160 "susan_edge_detector.cc"
SlaveHardwareBusLinkAccess::SlaveHardwareBusLinkAccess(ISlaveHardwareBusProtocol (&protocol))
    : _specc::channel(), protocol(protocol)
{   /* nothing */
}

SlaveHardwareBusLinkAccess::~SlaveHardwareBusLinkAccess(void)
{   /* nothing */
}

#line 254 "./HWBus.sc"
void SlaveHardwareBusLinkAccess::SlaveRead(int addr, void *data, unsigned long int len)
{   
    unsigned long int i;
    unsigned char *p;
    bit<_BITLEN(31,0),true> word;

    for(p = (unsigned char *)data , i = 0; i < len; i++  , p++ )
    {   
	if ( !(i % 4u)) {
	    protocol.slaveRead(addr,  &word);
	}

	 *p = ((unsigned char)((word(31,0, 31,24))).toInt());
	word = word << 8;
    }
}

#line 232 "./HWBus.sc"
void SlaveHardwareBusLinkAccess::SlaveWrite(int addr, const void *data, unsigned long int len)
{   
    unsigned long int i;
    unsigned char *p;
    bit<_BITLEN(31,0),true> word = bit<32,true>("00000000000000000000000000000000");

    for(p = (unsigned char *)data , i = 0; i < len; i++  , p++ )
    {   
	word = (word << 8) +  *p;

	if ( !((i + 1) % 4u)) {
	    protocol.slaveWrite(addr, word);
	    word = 0;
	}
    }

    if (i % 4u) {
	word <<= 8 * (4u - (i % 4u));
	protocol.slaveWrite(addr, word);
    }
}

#line 211 "susan_edge_detector.cc"
HardwareBus::HardwareBus()
    : _specc::channel(),
    MasterLink(TLM),
    MasterSync0(intr0),
    MasterSync1(intr1),
    SlaveLink(TLM),
    SlaveSync0(intr0),
    SlaveSync1(intr1),
    TLM(),
    intr0(),
    intr1()
{   /* nothing */
}

HardwareBus::~HardwareBus(void)
{   /* nothing */
}

#line 327 "./HWBus.sc"
void HardwareBus::MasterRead(bit<_BITLEN(15,0),true> addr, void *data, unsigned long int len) {
    MasterLink.MasterRead(((addr).toInt()), data, len);
}

#line 343 "./HWBus.sc"
void HardwareBus::MasterSyncReceive0() {
    MasterSync0.receive();
}
void HardwareBus::MasterSyncReceive1() {
    MasterSync1.receive();
}

#line 331 "./HWBus.sc"
void HardwareBus::MasterWrite(bit<_BITLEN(15,0),true> addr, const void *data, unsigned long int len) {
    MasterLink.MasterWrite(((addr).toInt()), data, len);
}

void HardwareBus::SlaveRead(bit<_BITLEN(15,0),true> addr, void *data, unsigned long int len) {
    SlaveLink.SlaveRead(((addr).toInt()), data, len);
}

#line 350 "./HWBus.sc"
void HardwareBus::SlaveSyncSend0() {
    SlaveSync0.send();
}

void HardwareBus::SlaveSyncSend1() {
    SlaveSync1.send();
}

#line 339 "./HWBus.sc"
void HardwareBus::SlaveWrite(bit<_BITLEN(15,0),true> addr, const void *data, unsigned long int len) {
    SlaveLink.SlaveWrite(((addr).toInt()), data, len);
}

#line 266 "susan_edge_detector.cc"
MasterDriveRead::MasterDriveRead(IMasterHardwareBus (&hdbus), OSAPI (&os))
    : _specc::channel(), hdbus(hdbus), os(os),
    addr(bit<16,false>("0000000000000001"))
{   /* nothing */
}

MasterDriveRead::~MasterDriveRead(void)
{   /* nothing */
}

#line 16 "./MasterDriveRead.sc"
void MasterDriveRead::receive(unsigned char *data) {

    task = os.pre_wait();
    hdbus.MasterSyncReceive0();
    hdbus.MasterRead(addr, data, 7220);
    os.post_wait(task);
}

#line 286 "susan_edge_detector.cc"
MasterDriveWrite::MasterDriveWrite(IMasterHardwareBus (&i_sender), OSAPI (&os))
    : _specc::channel(), i_sender(i_sender), os(os),
    addr(bit<16,false>("0000000000000010"))
{   /* nothing */
}

MasterDriveWrite::~MasterDriveWrite(void)
{   /* nothing */
}

#line 15 "./MasterDriveWrite.sc"
void MasterDriveWrite::send(unsigned char *data) {

    struct Task *task;
    task = os.pre_wait();
    i_sender.MasterSyncReceive1();
    i_sender.MasterWrite(addr, data, 7220);
    os.post_wait(task);
}

#line 307 "susan_edge_detector.cc"
SlaveDriveRead::SlaveDriveRead(ISlaveHardwareBus (&hdbus))
    : _specc::channel(), hdbus(hdbus),
    addr(bit<16,false>("0000000000000010"))
{   /* nothing */
}

SlaveDriveRead::~SlaveDriveRead(void)
{   /* nothing */
}

#line 14 "./SlaveDriveRead.sc"
void SlaveDriveRead::receive(unsigned char *data) {
    hdbus.SlaveSyncSend1();
    hdbus.SlaveRead(addr, data, 7220);
}

#line 324 "susan_edge_detector.cc"
SlaveDriveWrite::SlaveDriveWrite(ISlaveHardwareBus (&hdbus))
    : _specc::channel(), hdbus(hdbus),
    addr(bit<16,false>("0000000000000001"))
{   /* nothing */
}

SlaveDriveWrite::~SlaveDriveWrite(void)
{   /* nothing */
}

#line 14 "./SlaveDriveWrite.sc"
void SlaveDriveWrite::send(unsigned char *data) {
    hdbus.SlaveSyncSend0();
    hdbus.SlaveWrite(addr, data, 7220);
}

#line 341 "susan_edge_detector.cc"
c_double_handshake_signal::c_double_handshake_signal()
    : _specc::channel(),
    v(false),
    w(false)
{   /* nothing */
}

c_double_handshake_signal::~c_double_handshake_signal(void)
{   /* nothing */
}

#line 14 "./c_double_handshake_signal.sc"
void c_double_handshake_signal::receive(void)
{   
    if ( !v)
    {   
	w = true;
	_specc::wait(event(&req), ((void*)0));
	w = false;
    }
    v = false;
    _specc::notify(event(&ack), ((void*)0));
    _specc::wait(event(&ack), ((void*)0));
}

void c_double_handshake_signal::send(void)
{   
    v = true;
    if (w)
    {   
	_specc::notify(event(&req), ((void*)0));
    }
    _specc::wait(event(&ack), ((void*)0));
}

#line 377 "susan_edge_detector.cc"
c_uchar7220read_queue::c_uchar7220read_queue(const unsigned long int (&size), OSAPI (&os))
    : _specc::channel(), size(size), os(os),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_uchar7220read_queue::~c_uchar7220read_queue(void)
{   /* nothing */
}

#line 197 "./c_uchar7220read_queue.sc"
void c_uchar7220read_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 197 "./c_uchar7220read_queue.sc"
void c_uchar7220read_queue::receive(unsigned char (*d)[7220]) { struct Task *t; while( !n) { wr++ ; t = os.pre_wait(); _specc::wait(event(&r), ((void*)0)); os.post_wait(t); wr-- ;
    }

#line 197 "./c_uchar7220read_queue.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 197 "./c_uchar7220read_queue.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 197 "./c_uchar7220read_queue.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 197 "./c_uchar7220read_queue.sc"
    cleanup();
}

#line 197 "./c_uchar7220read_queue.sc"
void c_uchar7220read_queue::send(unsigned char d[7220]) { while(n >= size) { ws++ ; _specc::wait(event(&s), ((void*)0)); ws-- ;
    }

#line 197 "./c_uchar7220read_queue.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 197 "./c_uchar7220read_queue.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 197 "./c_uchar7220read_queue.sc"
void c_uchar7220read_queue::setup(void) { if ( !buffer) { unsigned char dummy[7220]; unsigned long int i; if ( !(buffer = (unsigned char (*)[7220])malloc(sizeof(unsigned char [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 197 "./c_uchar7220read_queue.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [7220]));
	}
    }
}

#line 441 "susan_edge_detector.cc"
c_uchar7220write_queue::c_uchar7220write_queue(const unsigned long int (&size), OSAPI (&os))
    : _specc::channel(), size(size), os(os),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_uchar7220write_queue::~c_uchar7220write_queue(void)
{   /* nothing */
}

#line 197 "./c_uchar7220write_queue.sc"
void c_uchar7220write_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 197 "./c_uchar7220write_queue.sc"
void c_uchar7220write_queue::receive(unsigned char (*d)[7220]) { while( !n) { wr++ ; _specc::wait(event(&r), ((void*)0)); wr-- ;
    }

#line 197 "./c_uchar7220write_queue.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 197 "./c_uchar7220write_queue.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 197 "./c_uchar7220write_queue.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 197 "./c_uchar7220write_queue.sc"
    cleanup();
}

#line 197 "./c_uchar7220write_queue.sc"
void c_uchar7220write_queue::send(unsigned char d[7220]) { struct Task *t; while(n >= size) { ws++ ; t = os.pre_wait(); _specc::wait(event(&s), ((void*)0)); os.post_wait(t); ws-- ;
    }

#line 197 "./c_uchar7220write_queue.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 197 "./c_uchar7220write_queue.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 197 "./c_uchar7220write_queue.sc"
void c_uchar7220write_queue::setup(void) { if ( !buffer) { unsigned char dummy[7220]; unsigned long int i; if ( !(buffer = (unsigned char (*)[7220])malloc(sizeof(unsigned char [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 197 "./c_uchar7220write_queue.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [7220]));
	}
    }
}

#line 505 "susan_edge_detector.cc"
OS::OS()
    : _specc::channel(),
    NextPt(0),
    NumCreated(0),
    RunPt(0),
    e1(),
    e10(),
    e11(),
    e12(),
    e13(),
    e14(),
    e15(),
    e2(),
    e3(),
    e4(),
    e5(),
    e6(),
    e7(),
    e8(),
    e9()
{   /* nothing */
}

OS::~OS(void)
{   /* nothing */
}

#line 82 "./os.sc"
void OS::Insert(struct Task *listPt, struct Task *currPt) {
    currPt->prev = listPt->prev;
    currPt->prev->next = currPt;
    currPt->next = listPt;
    listPt->prev = currPt;
}

#line 71 "./os.sc"
void OS::Remove(struct Task **listPt) {
    if ( *listPt == 0) return ;
    if (( *listPt)->next == ( *listPt)) {
	 *listPt = 0;
	return ;
    }
    ( *listPt)->prev->next = ( *listPt)->next;
    ( *listPt)->next->prev = ( *listPt)->prev;
     *listPt = ( *listPt)->prev;
}

#line 131 "./os.sc"
void OS::dispatch(void) {
    RunPt = RunPt->next;
    os_notify(RunPt->id);
}

#line 53 "./os.sc"
int OS::getNumCreated() {
    return NumCreated;
}

#line 144 "./os.sc"
void OS::init() {
}

#line 110 "./os.sc"
void OS::os_notify(int id) {
    switch(id) {
	case 1: e1.send(); break;
	case 2: e2.send(); break;
	case 3: e3.send(); break;
	case 4: e4.send(); break;
	case 5: e5.send(); break;
	case 6: e6.send(); break;
	case 7: e7.send(); break;
	case 8: e8.send(); break;
	case 9: e9.send(); break;
	case 10: e10.send(); break;
	case 11: e11.send(); break;
	case 12: e12.send(); break;
	case 13: e13.send(); break;
	case 14: e14.send(); break;
	case 15: e15.send(); break;
	default: break;
    }
}

#line 89 "./os.sc"
void OS::os_wait(int id) {
    switch(id) {
	case 1: e1.receive(); break;
	case 2: e2.receive(); break;
	case 3: e3.receive(); break;
	case 4: e4.receive(); break;
	case 5: e5.receive(); break;
	case 6: e6.receive(); break;
	case 7: e7.receive(); break;
	case 8: e8.receive(); break;
	case 9: e9.receive(); break;
	case 10: e10.receive(); break;
	case 11: e11.receive(); break;
	case 12: e12.receive(); break;
	case 13: e13.receive(); break;
	case 14: e14.receive(); break;
	case 15: e15.receive(); break;
	default: break;
    }
}

#line 202 "./os.sc"
void OS::par_end(struct Task *currPt) {
    if (RunPt == 0) {
	RunPt = currPt;
	RunPt->prev = RunPt->next = RunPt;
    }
    else 

#line 206 "./os.sc"
    {   
	Insert(RunPt, currPt);
	os_wait(currPt->id);
    }
    NumCreated++ ;
}

#line 191 "./os.sc"
struct Task *OS::par_start() {
    struct Task *currPt;
    currPt = RunPt;
    Remove( &RunPt);
    if (currPt) {
	NumCreated-- ;
    }
    if (RunPt) dispatch();
    return currPt;
}

#line 226 "./os.sc"
void OS::post_wait(struct Task *currPt) {
    if (RunPt == 0) {
	RunPt = currPt;
	RunPt->prev = RunPt->next = RunPt;
    }
    else 

#line 230 "./os.sc"
    {   
	Insert(RunPt, currPt);
	os_wait(currPt->id);
    }
    NumCreated++ ;
}

#line 215 "./os.sc"
struct Task *OS::pre_wait() {
    struct Task *currPt;
    currPt = RunPt;
    Remove( &RunPt);
    if (currPt) {
	NumCreated-- ;
    }
    if (RunPt) dispatch();
    return currPt;
}

#line 57 "./os.sc"
void OS::print() {
    struct Task *temp;
    if (RunPt == 0) { printf("Empty.\n"); return ;
    } temp = RunPt->next;
    printf("WaitQ: ");
    while(temp != RunPt) {
	printf("%d %s ", temp->id, temp->name);
	temp = temp->next;
    }
    printf("RunPt: %d %s \n", temp->id, temp->name);
    printf("Next:%d Run:%d\n", NextPt->id, RunPt->id);
    printf("end of queue.\n");
}

#line 148 "./os.sc"
void OS::start() {
}

#line 187 "./os.sc"
void OS::task_activate(struct Task *currPt) {
    os_wait(currPt->id);
}

#line 153 "./os.sc"
struct Task *OS::task_create(char *name) {
    int idx = 0;
    struct Task *currPt;
    if (NumCreated == 15) {
	return 0;
    }
    while(tasks[idx].id != 0) {
	idx++ ;
    }
    NumCreated++ ;
    currPt =  &tasks[idx];
    currPt->id = idx + 1;
    strcpy(currPt->name, name);
    if (RunPt == 0) {
	RunPt = currPt;
	RunPt->prev = RunPt->next = RunPt;
    }
    else 

#line 169 "./os.sc"
    {   
	Insert(RunPt, currPt);
    }
    NextPt = RunPt->next;
    return currPt;
}

void OS::task_terminate() {
    struct Task *currPt;
    currPt = RunPt;
    Remove( &RunPt);
    if (currPt) {
	currPt->id = 0;
	NumCreated-- ;
    }
    if (RunPt) dispatch();
}

#line 238 "./os.sc"
void OS::time_wait(unsigned long long int t) {
    _specc::waitfor((t));
    yield();
}

#line 136 "./os.sc"
void OS::yield() {
    struct Task *currPt;
    currPt = RunPt;
    dispatch();
    os_wait(currPt->id);
}

#line 745 "susan_edge_detector.cc"
c_double_handshake::c_double_handshake()
    : _specc::channel(),
    v(false),
    w(false)
{   /* nothing */
}

c_double_handshake::~c_double_handshake(void)
{   /* nothing */
}

#line 81 "c_double_handshake.sc"
void c_double_handshake::receive(void *d, unsigned long int l)
{   
    if ( !v)
    {   
	w = true;
	_specc::wait(event(&req), ((void*)0));
	w = false;
    }
    if (l != tmpl)
    {   
	abort();
    }
    memcpy(d, tmpd, l);
    v = false;
    _specc::notify(event(&ack), ((void*)0));
    _specc::wait(event(&ack), ((void*)0));
}

void c_double_handshake::send(const void *d, unsigned long int l)
{   
    tmpd = d;
    tmpl = l;
    v = true;
    if (w)
    {   
	_specc::notify(event(&req), ((void*)0));
    }
    _specc::wait(event(&ack), ((void*)0));
}

#line 788 "susan_edge_detector.cc"
c_handshake::c_handshake()
    : _specc::channel(),
    f(false),
    w(false)
{   /* nothing */
}

c_handshake::~c_handshake(void)
{   /* nothing */
}

#line 62 "c_handshake.sc"
void c_handshake::receive(void)
{   
    if ( !f)
    {   
	w = true;
	_specc::wait(event(&e), ((void*)0));
	w = false;
    }
    f = false;
}

void c_handshake::send(void)
{   
    if (w)
    {   
	_specc::notify(event(&e), ((void*)0));
    }
    f = true;
}

#line 821 "susan_edge_detector.cc"
c_int7220_queue::c_int7220_queue(const unsigned long int (&size), OSAPI (&os))
    : _specc::channel(), size(size), os(os),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_int7220_queue::~c_int7220_queue(void)
{   /* nothing */
}

#line 196 "c_int7220_queue.sc"
void c_int7220_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 196 "c_int7220_queue.sc"
void c_int7220_queue::receive(int (*d)[7220]) { struct Task *t; while( !n) { wr++ ; t = os.pre_wait(); _specc::wait(event(&r), ((void*)0)); os.post_wait(t); wr-- ;
    }

#line 196 "c_int7220_queue.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 196 "c_int7220_queue.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 196 "c_int7220_queue.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 196 "c_int7220_queue.sc"
    cleanup();
}

#line 196 "c_int7220_queue.sc"
void c_int7220_queue::send(int d[7220]) { struct Task *t1; while(n >= size) { ws++ ; t1 = os.pre_wait(); _specc::wait(event(&s), ((void*)0)); os.post_wait(t1); ws-- ;
    }

#line 196 "c_int7220_queue.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 196 "c_int7220_queue.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 196 "c_int7220_queue.sc"
void c_int7220_queue::setup(void) { if ( !buffer) { int dummy[7220]; unsigned long int i; if ( !(buffer = (int (*)[7220])malloc(sizeof(int [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 196 "c_int7220_queue.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(int [7220]));
	}
    }
}

#line 885 "susan_edge_detector.cc"
c_queue::c_queue(const unsigned long int (&size))
    : _specc::channel(), size(size),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_queue::~c_queue(void)
{   /* nothing */
}

#line 99 "c_queue.sc"
void c_queue::cleanup(void)
{   
    if ( !n)
    {   
	free(buffer);
	buffer = 0;
    }
}

void c_queue::receive(void *d, unsigned long int l)
{   
    unsigned long int p0;

    while(l > n)
    {   
	wr++ ;
	_specc::wait(event(&r), ((void*)0));
	wr-- ;
    }

    if (n <= p)
    {   
	p0 = p - n;
    }
    else 
    {   
	p0 = p + size - n;
    }
    if (l <= size - p0)
    {   
	memcpy(d,  &buffer[p0], l);
	n -= l;
    }
    else 
    {   
	memcpy(d,  &buffer[p0], size - p0);
	memcpy(((char *)d) + (size - p0),  &buffer[0], l - (size - p0));
	n -= l;
    }

    if (ws)
    {   
	_specc::notify(event(&s), ((void*)0));
    }

    cleanup();
}

void c_queue::send(const void *d, unsigned long int l)
{   
    while(l > size - n)
    {   
	ws++ ;
	_specc::wait(event(&s), ((void*)0));
	ws-- ;
    }

    setup();

    if (l <= size - p)
    {   
	memcpy( &buffer[p], d, l);
	p += l;
	n += l;
    }
    else 
    {   
	memcpy( &buffer[p], d, size - p);
	memcpy( &buffer[0], ((char *)d) + (size - p), l - (size - p));
	p = l - (size - p);
	n += l;
    }

    if (wr)
    {   
	_specc::notify(event(&r), ((void*)0));
    }
}

#line 87 "c_queue.sc"
void c_queue::setup(void)
{   
    if ( !buffer)
    {   
	if ( !(buffer = (char *)malloc(size)))
	{   
	    perror("c_queue");
	    abort();
	}
    }
}

#line 993 "susan_edge_detector.cc"
c_uchar7220_queue::c_uchar7220_queue(const unsigned long int (&size), OSAPI (&os))
    : _specc::channel(), size(size), os(os),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_uchar7220_queue::~c_uchar7220_queue(void)
{   /* nothing */
}

#line 197 "c_uchar7220_queue.sc"
void c_uchar7220_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 197 "c_uchar7220_queue.sc"
void c_uchar7220_queue::receive(unsigned char (*d)[7220]) { struct Task *t; while( !n) { wr++ ; t = os.pre_wait(); _specc::wait(event(&r), ((void*)0)); os.post_wait(t); wr-- ;
    }

#line 197 "c_uchar7220_queue.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 197 "c_uchar7220_queue.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 197 "c_uchar7220_queue.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 197 "c_uchar7220_queue.sc"
    cleanup();
}

#line 197 "c_uchar7220_queue.sc"
void c_uchar7220_queue::send(unsigned char d[7220]) { struct Task *t; while(n >= size) { ws++ ; t = os.pre_wait(); _specc::wait(event(&s), ((void*)0)); os.post_wait(t); ws-- ;
    }

#line 197 "c_uchar7220_queue.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 197 "c_uchar7220_queue.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 197 "c_uchar7220_queue.sc"
void c_uchar7220_queue::setup(void) { if ( !buffer) { unsigned char dummy[7220]; unsigned long int i; if ( !(buffer = (unsigned char (*)[7220])malloc(sizeof(unsigned char [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 197 "c_uchar7220_queue.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [7220]));
	}
    }
}

// behavior class definitions ////////////////////////////////////////

#line 1059 "susan_edge_detector.cc"
INPUT::INPUT(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], ISlaveHardwareBus (&hdbus))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), hdbus(hdbus),
    read_image(++_IDcnt, start, image_buffer, slave_drive_write),
    slave_drive_write(hdbus)
{   /* nothing */
}

INPUT::~INPUT(void)
{   /* nothing */
}

#line 19 "./input.sc"
void INPUT::main(void) {
    { _specc::fork _scc_fork_0(&read_image); _specc::par(
	    &_scc_fork_0, ((_specc::fork*)0));
    }
}

#line 1078 "susan_edge_detector.cc"
OUTPUT::OUTPUT(unsigned int _idcnt, ISlaveHardwareBus (&hdbus), i_sender (&out_image))
    : _specc::behavior(_idcnt), hdbus(hdbus), out_image(out_image),
    slave_drive_read(hdbus),
    write_image(++_IDcnt, out_image, slave_drive_read)
{   /* nothing */
}

OUTPUT::~OUTPUT(void)
{   /* nothing */
}

#line 19 "./output.sc"
void OUTPUT::main(void) {
    { _specc::fork _scc_fork_0(&write_image); _specc::par(
	    &_scc_fork_0, ((_specc::fork*)0));
    }
}

#line 1097 "susan_edge_detector.cc"
PE1::PE1(unsigned int _idcnt, OSAPI (&os), IMasterHardwareBus (&hdbus))
    : _specc::behavior(_idcnt), os(os), hdbus(hdbus),
    master_driver_read(hdbus, os),
    master_driver_write(hdbus, os),
    task_pe1(_IDcnt, master_driver_read, master_driver_write, os)
{   /* nothing */
}

PE1::~PE1(void)
{   /* nothing */
}

#line 30 "./pe1.sc"
void PE1::main(void)
{   
    task_pe1.main();
}

#line 1116 "susan_edge_detector.cc"
TASK_PE1::TASK_PE1(unsigned int _idcnt, master_receiver (&in_image), master_sender (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), out_image(out_image), os(os),
    _scc_const_port_0(1ul),
    _scc_const_port_1(1ul),
    _scc_const_port_2(1ul),
    _scc_const_port_3(1ul),
    draw(_IDcnt, image_edge_draw, mid_edge_draw, out_image, os),
    edges(_IDcnt, in_image, r, mid, image_edge_draw, os),
    image_edge_draw(_scc_const_port_0, os),
    mid(_scc_const_port_1, os),
    mid_edge_draw(_scc_const_port_2, os),
    r(_scc_const_port_3, os),
    thin(_IDcnt, r, mid, mid_edge_draw, os)
{   /* nothing */
}

TASK_PE1::~TASK_PE1(void)
{   /* nothing */
}

#line 36 "./task_pe1.sc"
void TASK_PE1::init(void) {
    task = os.task_create("pe1");
}


void TASK_PE1::main(void)
{   
    init();
    edges.init();
    thin.init();
    draw.init();

    task = os.par_start();
    { _specc::fork _scc_fork_0(&edges), _scc_fork_1(&thin), _scc_fork_2(&draw); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }
    os.par_end(task);

    os.task_terminate();
}

#line 1161 "susan_edge_detector.cc"
Design::Design(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], i_sender (&out_image_susan))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), out_image_susan(out_image_susan),
    hdbus(),
    input(++_IDcnt, start, image_buffer, hdbus),
    os(),
    output(++_IDcnt, hdbus, out_image_susan),
    pe1(++_IDcnt, os, hdbus)
{   /* nothing */
}

Design::~Design(void)
{   /* nothing */
}

#line 33 "design.sc"
void Design::main(void) {
    { _specc::fork _scc_fork_0(&input), _scc_fork_1(&pe1), _scc_fork_2(&output); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }
}

#line 1185 "susan_edge_detector.cc"
DetectEdges::DetectEdges(unsigned int _idcnt, master_receiver (&in_image), i_int7220_sender (&out_r), i_uchar7220_sender (&out_mid), i_uchar7220_sender (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), out_r(out_r), out_mid(out_mid), out_image(out_image), os(os),
    setup(_IDcnt, in_image, image_buffer, bp, os),
    susan_edges(_IDcnt, image_buffer, out_r, out_mid, bp, out_image, os)
{   /* nothing */
}

DetectEdges::~DetectEdges(void)
{   /* nothing */
}

#line 21 "detect_edges.sc"
void DetectEdges::main(void) {
    setup.main();
    susan_edges.main();
}

#line 1203 "susan_edge_detector.cc"
Edges::Edges(unsigned int _idcnt, master_receiver (&in_image), i_int7220_sender (&out_r), i_uchar7220_sender (&out_mid), i_uchar7220_sender (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), out_r(out_r), out_mid(out_mid), out_image(out_image), os(os),
    detect_edges(_IDcnt, in_image, out_r, out_mid, out_image, os)
{   /* nothing */
}

Edges::~Edges(void)
{   /* nothing */
}

#line 34 "detect_edges.sc"
void Edges::init(void) {
    task = os.task_create("edge");
}

void Edges::main(void) {
    os.task_activate(task);
    { enum { _scc_state_0, _scc_state_detect_edges } _scc_next_state = _scc_state_detect_edges; do switch(_scc_next_state) {
	    case _scc_state_detect_edges: { detect_edges.main(); { _scc_next_state = _scc_state_detect_edges; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
    os.task_terminate();
}

#line 1227 "susan_edge_detector.cc"
EdgeDrawThread_PartA::EdgeDrawThread_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), thID(thID), os(os)
{   /* nothing */
}

EdgeDrawThread_PartA::~EdgeDrawThread_PartA(void)
{   /* nothing */
}

#line 17 "edge_draw.sc"
void EdgeDrawThread_PartA::init(void) {
    task = os.task_create("ed_a_t");
}

void EdgeDrawThread_PartA::main(void) {

    int i;
    unsigned char *inp; unsigned char *midp;
    int drawing_mode;
    drawing_mode = 0;

    os.task_activate(task);

    if (drawing_mode == 0)
    {   

	midp = mid + 7220 / 2 * thID;

	for(i = 76 * 95 / 2 * thID; i < 76 * 95 / 2 * (thID + 1) + (thID + 1 == 2 && 76 * 95 % 2 != 0 ? 76 * 95 % 2 : 0); i++ )
	{   
	    if ( *midp < 8)
	    {   
		inp = image_buffer + (midp - mid) - 76 - 1;
		 *inp++  = 255;  *inp++  = 255;  *inp = 255; inp += 76 - 2;
		 *inp++  = 255;  *inp++ ;  *inp = 255; inp += 76 - 2;
		 *inp++  = 255;  *inp++  = 255;  *inp = 255;
	    }
	    midp++ ;
	    os.time_wait(12000000);
	}
    }

    os.task_terminate();
}

#line 1273 "susan_edge_detector.cc"
EdgeDrawThread_PartB::EdgeDrawThread_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), thID(thID), os(os)
{   /* nothing */
}

EdgeDrawThread_PartB::~EdgeDrawThread_PartB(void)
{   /* nothing */
}

#line 58 "edge_draw.sc"
void EdgeDrawThread_PartB::init(void) {
    task = os.task_create("ed_b_t");
}

void EdgeDrawThread_PartB::main(void) {

    int i;
    unsigned char *midp;
    int drawing_mode;

    drawing_mode = 0;


    midp = mid + 7220 / 2 * thID;


    os.task_activate(task);

    for(i = 76 * 95 / 2 * thID; i < 76 * 95 / 2 * (thID + 1) + (thID + 1 == 2 && 76 * 95 % 2 != 0 ? 76 * 95 % 2 : 0); i++ )
    {   
	if ( *midp < 8)
	     *(image_buffer + (midp - mid)) = 0;
	midp++ ;
	os.time_wait(12000000);
    }

    os.task_terminate();
}

#line 1313 "susan_edge_detector.cc"
EdgeDraw_ReadInput::EdgeDraw_ReadInput(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_uchar7220_receiver (&in_mid), unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), in_image(in_image), in_mid(in_mid), image_buffer(image_buffer), mid(mid)
{   /* nothing */
}

EdgeDraw_ReadInput::~EdgeDraw_ReadInput(void)
{   /* nothing */
}

#line 91 "edge_draw.sc"
void EdgeDraw_ReadInput::main(void) {
    in_image.receive( &image_buffer);
    in_mid.receive( &mid);
}

#line 1329 "susan_edge_detector.cc"
EdgeDraw_WriteOutput::EdgeDraw_WriteOutput(unsigned int _idcnt, unsigned char (&image_buffer)[7220], master_sender (&out_image))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), out_image(out_image)
{   /* nothing */
}

EdgeDraw_WriteOutput::~EdgeDraw_WriteOutput(void)
{   /* nothing */
}

#line 99 "edge_draw.sc"
void EdgeDraw_WriteOutput::main(void) {
    out_image.send(image_buffer);
}

#line 1344 "susan_edge_detector.cc"
EdgeDraw_PartA::EdgeDraw_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    edge_draw_a_thread_0(_IDcnt, image_buffer, mid, _scc_const_port_0, os),
    edge_draw_a_thread_1(_IDcnt, image_buffer, mid, _scc_const_port_1, os)
{   /* nothing */
}

EdgeDraw_PartA::~EdgeDraw_PartA(void)
{   /* nothing */
}

#line 110 "edge_draw.sc"
void EdgeDraw_PartA::main(void) {
    edge_draw_a_thread_0.init();
    edge_draw_a_thread_1.init();

    task = os.par_start();
    { _specc::fork _scc_fork_0(&edge_draw_a_thread_0), _scc_fork_1(&edge_draw_a_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(task);
}

#line 1371 "susan_edge_detector.cc"
EdgeDraw_PartB::EdgeDraw_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    edge_draw_b_thread_0(_IDcnt, image_buffer, mid, _scc_const_port_0, os),
    edge_draw_b_thread_1(_IDcnt, image_buffer, mid, _scc_const_port_1, os)
{   /* nothing */
}

EdgeDraw_PartB::~EdgeDraw_PartB(void)
{   /* nothing */
}

#line 129 "edge_draw.sc"
void EdgeDraw_PartB::main(void) {
    edge_draw_b_thread_0.init();
    edge_draw_b_thread_1.init();

    task = os.par_start();
    { _specc::fork _scc_fork_0(&edge_draw_b_thread_0), _scc_fork_1(&edge_draw_b_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(task);
}

#line 1398 "susan_edge_detector.cc"
EdgeDraw::EdgeDraw(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_uchar7220_receiver (&in_mid), master_sender (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), in_mid(in_mid), out_image(out_image), os(os),
    edge_draw_a(_IDcnt, image_buffer, mid, os),
    edge_draw_b(_IDcnt, image_buffer, mid, os),
    edge_draw_read_input(_IDcnt, in_image, in_mid, image_buffer, mid),
    edge_draw_write_output(_IDcnt, image_buffer, out_image)
{   /* nothing */
}

EdgeDraw::~EdgeDraw(void)
{   /* nothing */
}

#line 155 "edge_draw.sc"
void EdgeDraw::main(void) {

    { enum { _scc_state_0, _scc_state_edge_draw_read_input, _scc_state_edge_draw_a, _scc_state_edge_draw_b, _scc_state_edge_draw_write_output } _scc_next_state = _scc_state_edge_draw_read_input; do switch(_scc_next_state) {
	    case _scc_state_edge_draw_read_input: { edge_draw_read_input.main(); { _scc_next_state = _scc_state_edge_draw_a; break; } }
	    case _scc_state_edge_draw_a: { edge_draw_a.main(); { _scc_next_state = _scc_state_edge_draw_b; break; } }
	    case _scc_state_edge_draw_b: { edge_draw_b.main(); { _scc_next_state = _scc_state_edge_draw_write_output; break; } }
	    case _scc_state_edge_draw_write_output: { edge_draw_write_output.main(); { _scc_next_state = _scc_state_0; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
}

#line 1423 "susan_edge_detector.cc"
Draw::Draw(unsigned int _idcnt, i_uchar7220_receiver (&in_image), i_uchar7220_receiver (&in_mid), master_sender (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), in_mid(in_mid), out_image(out_image), os(os),
    edge_draw(_IDcnt, in_image, in_mid, out_image, os)
{   /* nothing */
}

Draw::~Draw(void)
{   /* nothing */
}

#line 171 "edge_draw.sc"
void Draw::init(void) {
    task = os.task_create("draw");
}

void Draw::main(void) {

    os.task_activate(task);
    { enum { _scc_state_0, _scc_state_edge_draw } _scc_next_state = _scc_state_edge_draw; do switch(_scc_next_state) {
	    case _scc_state_edge_draw: { edge_draw.main(); { _scc_next_state = _scc_state_edge_draw; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
    os.task_terminate();
}

#line 1448 "susan_edge_detector.cc"
Monitor::Monitor(unsigned int _idcnt, i_receiver (&img), i_receiver (&start_time_channel))
    : _specc::behavior(_idcnt), img(img), start_time_channel(start_time_channel)
{   /* nothing */
}

Monitor::~Monitor(void)
{   /* nothing */
}

#line 10 "monitor.sc"
void Monitor::main(void)
{   
    struct _IO_FILE *fd;
    unsigned char image_buffer[7220];
    char filename[100];
    int n;
    unsigned long long int start_time;
    for(n = 0; n < 5; n++ )
    {   
	start_time_channel.receive( &start_time, sizeof(unsigned long long int));
	sprintf(filename, "out.pgm");




	if ((fd = fopen(filename, "w")) == ((void *)0))

	{    fprintf(stderr, "Can't output image%s.\n", filename); exit(0);
	}

#line 27 "monitor.sc"
	;

	fprintf(fd, "P5\n");
	fprintf(fd, "%d %d\n", 76, 95);
	fprintf(fd, "255\n");

	img.receive(image_buffer, 7220 * sizeof(char));

	if (fwrite(image_buffer, 76 * 95, 1, fd) != 1)
	{    fprintf(stderr, "Can't write image %s.\n", filename); exit(0);
	}

#line 36 "monitor.sc"
	;

	fclose(fd);
	printf("Total process time: %llu us\n", (now() - start_time) / (1 * 1000000ull));
    }

    printf("Current time: %llu us\n", (now()) / (1 * 1000000ull));
    exit(0);
}

#line 1503 "susan_edge_detector.cc"
ReadImage::ReadImage(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], slave_sender (&out_image))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), out_image(out_image)
{   /* nothing */
}

ReadImage::~ReadImage(void)
{   /* nothing */
}

#line 11 "read_image.sc"
void ReadImage::main(void) {
    int i;
    unsigned char image_buffer_out[7220];

    while(true) {
	start.receive();
	for(i = 0; i < 7220; i++ )
	    image_buffer_out[i] = image_buffer[i];
	out_image.send(image_buffer_out);
    }
}

#line 1526 "susan_edge_detector.cc"
SetupBrightnessLutThread::SetupBrightnessLutThread(unsigned int _idcnt, unsigned char (&bp)[516], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), bp(bp), thID(thID), os(os)
{   /* nothing */
}

SetupBrightnessLutThread::~SetupBrightnessLutThread(void)
{   /* nothing */
}

#line 16 "setup_brightness_lut.sc"
void SetupBrightnessLutThread::init(void) {
    task = os.task_create("sbl_t");
}


void SetupBrightnessLutThread::main(void) {
    int k;
    float temp;
    int form; int thresh;

    thresh = 20;
    form = 6;

    os.task_activate(task);

    for(k = ( -256) + 512 / 2 * thID; k < ( -256) + 512 / 2 * thID + 512 / 2 + 1; k++ ) {

	temp = ((float)k) / ((float)thresh);
	temp = temp * temp;
	if (form == 6)
	    temp = temp * temp * temp;
	temp = 1.000000000000000e+02 * exp( -temp);
	bp[(k + 258)] = (unsigned char)temp;

	os.time_wait(2700);
    }
    os.task_terminate();
}

#line 1566 "susan_edge_detector.cc"
SetupBrightnessLut_ReadInput::SetupBrightnessLut_ReadInput(unsigned int _idcnt, master_receiver (&in_image), unsigned char (&in_image_buffer)[7220])
    : _specc::behavior(_idcnt), in_image(in_image), in_image_buffer(in_image_buffer)
{   /* nothing */
}

SetupBrightnessLut_ReadInput::~SetupBrightnessLut_ReadInput(void)
{   /* nothing */
}

#line 49 "setup_brightness_lut.sc"
void SetupBrightnessLut_ReadInput::main(void) {
    in_image.receive(in_image_buffer);
}

#line 1581 "susan_edge_detector.cc"
SetupBrightnessLut::SetupBrightnessLut(unsigned int _idcnt, unsigned char (&bp)[516], OSAPI (&os))
    : _specc::behavior(_idcnt), bp(bp), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    setup_brightness_thread_0(_IDcnt, bp, _scc_const_port_0, os),
    setup_brightness_thread_1(_IDcnt, bp, _scc_const_port_1, os)
{   /* nothing */
}

SetupBrightnessLut::~SetupBrightnessLut(void)
{   /* nothing */
}

#line 61 "setup_brightness_lut.sc"
void SetupBrightnessLut::main(void) {
    setup_brightness_thread_0.init();
    setup_brightness_thread_1.init();

    task = os.par_start();
    { _specc::fork _scc_fork_0(&setup_brightness_thread_0), _scc_fork_1(&setup_brightness_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(task);
}

#line 1608 "susan_edge_detector.cc"
SetupBright::SetupBright(unsigned int _idcnt, master_receiver (&in_image), unsigned char (&image_buffer)[7220], unsigned char (&bp)[516], OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), image_buffer(image_buffer), bp(bp), os(os),
    setup(_IDcnt, bp, os),
    setup_read_input(_IDcnt, in_image, image_buffer)
{   /* nothing */
}

SetupBright::~SetupBright(void)
{   /* nothing */
}

#line 79 "setup_brightness_lut.sc"
void SetupBright::main(void) {
    { enum { _scc_state_0, _scc_state_setup_read_input, _scc_state_setup } _scc_next_state = _scc_state_setup_read_input; do switch(_scc_next_state) {
	    case _scc_state_setup_read_input: { setup_read_input.main(); { _scc_next_state = _scc_state_setup; break; } }
	    case _scc_state_setup: { setup.main(); { _scc_next_state = _scc_state_0; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
}

#line 1628 "susan_edge_detector.cc"
Stimulus::Stimulus(unsigned int _idcnt, i_send (&start), unsigned char (&image_buffer)[7220], i_sender (&start_time_channel))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), start_time_channel(start_time_channel)
{   /* nothing */
}

Stimulus::~Stimulus(void)
{   /* nothing */
}

#line 41 "stimulus.sc"
void Stimulus::get_image(char filename[200], unsigned char *image)
{   

    struct _IO_FILE *fd;
    char header[100];
    int tmp; int x_size; int y_size;

#line 52 "stimulus.sc"
    if ((fd = fopen(filename, "r")) == ((void *)0))

    {    fprintf(stderr, "Can't input image %s.\n", filename); exit(0);
    }

#line 54 "stimulus.sc"
    ;


    header[0] = fgetc(fd);
    header[1] = fgetc(fd);
    if ( !(header[0] == 'P' && header[1] == '5'))
    {    fprintf(stderr, "Image %s does not have binary PGM header.\n", filename); exit(0);
    }

#line 60 "stimulus.sc"
    ;

    x_size = getint(fd);
    y_size = getint(fd);
    tmp = getint(fd);

    if ((x_size != 76) || (y_size != 95)) {
	fprintf(stderr, "Input picture does not match size of %dx%d\n", 76, 95);
	fclose(fd);
	exit(1);
    }

    if (fread(image, 1, 76 * 95, fd) == 0)
    {    fprintf(stderr, "Image %s is wrong size.\n", filename); exit(0);
    }

#line 73 "stimulus.sc"
    ;
    fclose(fd);
}

#line 11 "stimulus.sc"
int Stimulus::getint(struct _IO_FILE *fd)
{   
    int c; int i;
    char dummy[10000];

    c = _IO_getc(fd);
    while(1)
    {   
	if (c == '#')
	    fgets(dummy, 9000, fd);
	if (c == ( -1))
	{    fprintf(stderr, "Image %s not binary PGM.\n", "is"); exit(0);
	}

#line 22 "stimulus.sc"
	;
	if (c >= '0' && c <= '9')
	    break;
	c = _IO_getc(fd);
    }


    i = 0;
    while(1) {
	i = (i * 10) + (c - '0');
	c = _IO_getc(fd);
	if (c == ( -1)) return (i);
	if (c < '0' || c > '9') break;
    }

    return (i);
}

#line 77 "stimulus.sc"
void Stimulus::main(void)
{   
    unsigned int n;
    char filename[100];
    unsigned long long int start_time;

    sprintf(filename, "%s", "input_small.pgm");
    get_image(filename, image_buffer);
    for(n = 0; n < 5; n++ ) {
	printf("Starting process %d...\n", n + 1);
	start.send();
	start_time = now();
	start_time_channel.send( &start_time, sizeof(unsigned long long int));
	_specc::waitfor((1000));
    }
}

#line 1736 "susan_edge_detector.cc"
Main::Main(unsigned int _idcnt)
    : _specc::class_type(_idcnt),
    _scc_const_port_0(1000ul),
    design(_IDcnt, start, image_buffer, out_image),
    monitor(_IDcnt, out_image, start_time),
    out_image(),
    start(),
    start_time(_scc_const_port_0),
    stimulus(_IDcnt, start, image_buffer, start_time)
{   /* nothing */
}

Main::~Main(void)
{   /* nothing */
}

#line 21 "susan_edge_detector.sc"
int Main::main(void) {
    { _specc::fork _scc_fork_0(&stimulus), _scc_fork_1(&design), _scc_fork_2(&monitor); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }

    return 0;
}

#line 1764 "susan_edge_detector.cc"
Main _scc_main(_IDcnt);

int main(void)
{   
    int _scc_main_return;
    
    _specc::start();
    _scc_main_return = _scc_main.main();
    _specc::end();
    return(_scc_main_return);
}

SusanEdgesThread_PartA::SusanEdgesThread_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&bp)[516], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), bp(bp), thID(thID), os(os)
{   /* nothing */
}

SusanEdgesThread_PartA::~SusanEdgesThread_PartA(void)
{   /* nothing */
}

#line 17 "susan_edges.sc"
void SusanEdgesThread_PartA::init(void) {
    task = os.task_create("se_a_t");
}

void SusanEdgesThread_PartA::main(void) {

    int max_no;
    int i; int j; int n;
    unsigned char *cp; unsigned char *p;

    max_no = 2650;


    os.task_activate(task);

    for(i = 3 + (95 - 3 - 3) / 2 * thID; i < 3 + (95 - 3 - 3) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 3 - 3) % 2 != 0 ? (95 - 3 - 3) % 2 : 0); i++ )
    {   
	for(j = 3; j < 76 - 3; j++ )
	{   
	    n = 100;
	    p = image_buffer + (i - 3) * 76 + j - 1;
	    cp = bp + 258 + image_buffer[i * 76 + j];

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 3;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 5;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 6;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 2;
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 6;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 5;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 3;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);

	    if (n <= max_no)
		r[i * 76 + j] = max_no - n;
	}

	os.time_wait(19000000);
    }
    os.task_terminate();
}

#line 1869 "susan_edge_detector.cc"
SusanEdgesThread_PartB::SusanEdgesThread_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&bp)[516], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), mid(mid), bp(bp), thID(thID), os(os)
{   /* nothing */
}

SusanEdgesThread_PartB::~SusanEdgesThread_PartB(void)
{   /* nothing */
}

#line 105 "susan_edges.sc"
void SusanEdgesThread_PartB::init(void) {
    task = os.task_create("se_b_t");
}

void SusanEdgesThread_PartB::main(void) {

    int max_no;
    float z;
    int a; int b; int do_symmetry; int i; int j; int m; int n; int w; int x; int y;
    unsigned char c; unsigned char *cp; unsigned char *p;

    max_no = 2650;

    os.task_activate(task);


    for(i = 4 + (95 - 4 - 4) / 2 * thID; i < 4 + (95 - 4 - 4) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 4 - 4) % 2 != 0 ? (95 - 4 - 4) % 2 : 0); i++ )
    {   

	for(j = 4; j < 76 - 4; j++ )
	{   
	    if (r[i * 76 + j] > 0)
	    {   
		m = r[i * 76 + j];
		n = max_no - m;
		cp = bp + 258 + image_buffer[i * 76 + j];

		if (n > 600)
		{   
		    p = image_buffer + (i - 3) * 76 + j - 1;
		    x = 0; y = 0;

		    c =  *(cp -  *p++ ); x -= c; y -= 3 * c;
		    c =  *(cp -  *p++ ); y -= 3 * c;
		    c =  *(cp -  *p); x += c; y -= 3 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x -= 2 * c; y -= 2 * c;
		    c =  *(cp -  *p++ ); x -= c; y -= 2 * c;
		    c =  *(cp -  *p++ ); y -= 2 * c;
		    c =  *(cp -  *p++ ); x += c; y -= 2 * c;
		    c =  *(cp -  *p); x += 2 * c; y -= 2 * c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x -= 3 * c; y -= c;
		    c =  *(cp -  *p++ ); x -= 2 * c; y -= c;
		    c =  *(cp -  *p++ ); x -= c; y -= c;
		    c =  *(cp -  *p++ ); y -= c;
		    c =  *(cp -  *p++ ); x += c; y -= c;
		    c =  *(cp -  *p++ ); x += 2 * c; y -= c;
		    c =  *(cp -  *p); x += 3 * c; y -= c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x -= 3 * c;
		    c =  *(cp -  *p++ ); x -= 2 * c;
		    c =  *(cp -  *p); x -= c;
		    p += 2;
		    c =  *(cp -  *p++ ); x += c;
		    c =  *(cp -  *p++ ); x += 2 * c;
		    c =  *(cp -  *p); x += 3 * c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x -= 3 * c; y += c;
		    c =  *(cp -  *p++ ); x -= 2 * c; y += c;
		    c =  *(cp -  *p++ ); x -= c; y += c;
		    c =  *(cp -  *p++ ); y += c;
		    c =  *(cp -  *p++ ); x += c; y += c;
		    c =  *(cp -  *p++ ); x += 2 * c; y += c;
		    c =  *(cp -  *p); x += 3 * c; y += c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x -= 2 * c; y += 2 * c;
		    c =  *(cp -  *p++ ); x -= c; y += 2 * c;
		    c =  *(cp -  *p++ ); y += 2 * c;
		    c =  *(cp -  *p++ ); x += c; y += 2 * c;
		    c =  *(cp -  *p); x += 2 * c; y += 2 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x -= c; y += 3 * c;
		    c =  *(cp -  *p++ ); y += 3 * c;
		    c =  *(cp -  *p); x += c; y += 3 * c;

		    z = sqrt((float)((x * x) + (y * y)));
		    if (z > (9.000000000000000e-01 * (float)n))
		    {   
			do_symmetry = 0;
			if (x == 0)
			    z = 1.000000000000000e+06;
			else 
			    z = ((float)y) / ((float)x);
			if (z < 0) { z =  -z; w =  -1;
			}
			else 

#line 196 "susan_edges.sc"
			    w = 1;
			if (z < 5.000000000000000e-01) { a = 0; b = 1;
			}
			else 

#line 198 "susan_edges.sc"
			{    if (z > 2.000000000000000e+00) { a = 1; b = 0;
			    }
			    else 

#line 199 "susan_edges.sc"
			    {    if (w > 0) { a = 1; b = 1;
				}
				else 

#line 200 "susan_edges.sc"
				{    a =  -1; b = 1;
				}
			    }
			}

#line 201 "susan_edges.sc"
			if ((m > r[(i + a) * 76 + j + b]) && (m >= r[(i - a) * 76 + j - b]) && 
			    (m > r[(i + (2 * a)) * 76 + j + (2 * b)]) && (m >= r[(i - (2 * a)) * 76 + j - (2 * b)]))
			    mid[i * 76 + j] = 1;
		    }
		    else 
			do_symmetry = 1;
		}
		else 
		    do_symmetry = 1;

		if (do_symmetry == 1)
		{   
		    p = image_buffer + (i - 3) * 76 + j - 1;
		    x = 0; y = 0; w = 0;

#line 220 "susan_edges.sc"
		    c =  *(cp -  *p++ ); x += c; y += 9 * c; w += 3 * c;
		    c =  *(cp -  *p++ ); y += 9 * c;
		    c =  *(cp -  *p); x += c; y += 9 * c; w -= 3 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x += 4 * c; y += 4 * c; w += 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w += 2 * c;
		    c =  *(cp -  *p++ ); y += 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w -= 2 * c;
		    c =  *(cp -  *p); x += 4 * c; y += 4 * c; w -= 4 * c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x += 9 * c; y += c; w += 3 * c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w += 2 * c;
		    c =  *(cp -  *p++ ); x += c; y += c; w += c;
		    c =  *(cp -  *p++ ); y += c;
		    c =  *(cp -  *p++ ); x += c; y += c; w -= c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w -= 2 * c;
		    c =  *(cp -  *p); x += 9 * c; y += c; w -= 3 * c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x += 9 * c;
		    c =  *(cp -  *p++ ); x += 4 * c;
		    c =  *(cp -  *p); x += c;
		    p += 2;
		    c =  *(cp -  *p++ ); x += c;
		    c =  *(cp -  *p++ ); x += 4 * c;
		    c =  *(cp -  *p); x += 9 * c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x += 9 * c; y += c; w -= 3 * c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w -= 2 * c;
		    c =  *(cp -  *p++ ); x += c; y += c; w -= c;
		    c =  *(cp -  *p++ ); y += c;
		    c =  *(cp -  *p++ ); x += c; y += c; w += c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w += 2 * c;
		    c =  *(cp -  *p); x += 9 * c; y += c; w += 3 * c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x += 4 * c; y += 4 * c; w -= 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w -= 2 * c;
		    c =  *(cp -  *p++ ); y += 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w += 2 * c;
		    c =  *(cp -  *p); x += 4 * c; y += 4 * c; w += 4 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x += c; y += 9 * c; w -= 3 * c;
		    c =  *(cp -  *p++ ); y += 9 * c;
		    c =  *(cp -  *p); x += c; y += 9 * c; w += 3 * c;

		    if (y == 0)
			z = 1.000000000000000e+06;
		    else 
			z = ((float)x) / ((float)y);
		    if (z < 5.000000000000000e-01) { a = 0; b = 1;
		    }
		    else 

#line 275 "susan_edges.sc"
		    {    if (z > 2.000000000000000e+00) { a = 1; b = 0;
			}
			else 

#line 276 "susan_edges.sc"
			{    if (w > 0) { a =  -1; b = 1;
			    }
			    else 

#line 277 "susan_edges.sc"
			    {    a = 1; b = 1;
			    }
			}
		    }

#line 278 "susan_edges.sc"
		    if ((m > r[(i + a) * 76 + j + b]) && (m >= r[(i - a) * 76 + j - b]) && 
			(m > r[(i + (2 * a)) * 76 + j + (2 * b)]) && (m >= r[(i - (2 * a)) * 76 + j - (2 * b)]))
			mid[i * 76 + j] = 2;
		}
	    }
	}

	os.time_wait(20000000);
    }

    os.task_terminate();
}

#line 2101 "susan_edge_detector.cc"
SusanEdges_ReadInput::SusanEdges_ReadInput(unsigned int _idcnt, int (&r)[7220], unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), r(r), mid(mid)
{   /* nothing */
}

SusanEdges_ReadInput::~SusanEdges_ReadInput(void)
{   /* nothing */
}

#line 295 "susan_edges.sc"
void SusanEdges_ReadInput::main(void) {
    memset(mid, 100, 76 * 95);
    memset(r, 0, 76 * 95 * sizeof(int));
}

#line 2117 "susan_edge_detector.cc"
SusanEdges_WriteOutput::SusanEdges_WriteOutput(unsigned int _idcnt, i_int7220_sender (&out_r), i_uchar7220_sender (&out_mid), i_uchar7220_sender (&out_image), int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&out_image_buffer)[7220])
    : _specc::behavior(_idcnt), out_r(out_r), out_mid(out_mid), out_image(out_image), r(r), mid(mid), out_image_buffer(out_image_buffer)
{   /* nothing */
}

SusanEdges_WriteOutput::~SusanEdges_WriteOutput(void)
{   /* nothing */
}

#line 306 "susan_edges.sc"
void SusanEdges_WriteOutput::main(void) {
    out_r.send(r);
    out_mid.send(mid);
    out_image.send(out_image_buffer);
}

#line 2134 "susan_edge_detector.cc"
SusanEdges_PartA::SusanEdges_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&bp)[516], OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), bp(bp), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    susan_edges_a_thread_0(_IDcnt, image_buffer, r, bp, _scc_const_port_0, os),
    susan_edges_a_thread_1(_IDcnt, image_buffer, r, bp, _scc_const_port_1, os)
{   /* nothing */
}

SusanEdges_PartA::~SusanEdges_PartA(void)
{   /* nothing */
}

#line 319 "susan_edges.sc"
void SusanEdges_PartA::main(void) {
    susan_edges_a_thread_0.init();
    susan_edges_a_thread_1.init();

    task = os.par_start();
    { _specc::fork _scc_fork_0(&susan_edges_a_thread_0), _scc_fork_1(&susan_edges_a_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(task);
}

#line 2161 "susan_edge_detector.cc"
SusanEdges_PartB::SusanEdges_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&bp)[516], OSAPI (&os))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), mid(mid), bp(bp), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    susan_edges_b_thread_0(_IDcnt, image_buffer, r, mid, bp, _scc_const_port_0, os),
    susan_edges_b_thread_1(_IDcnt, image_buffer, r, mid, bp, _scc_const_port_1, os)
{   /* nothing */
}

SusanEdges_PartB::~SusanEdges_PartB(void)
{   /* nothing */
}

#line 338 "susan_edges.sc"
void SusanEdges_PartB::main(void) {
    susan_edges_b_thread_0.init();
    susan_edges_b_thread_1.init();

    task = os.par_start();
    { _specc::fork _scc_fork_0(&susan_edges_b_thread_0), _scc_fork_1(&susan_edges_b_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(task);
}

#line 2188 "susan_edge_detector.cc"
SusanEdges::SusanEdges(unsigned int _idcnt, unsigned char (&in_image)[7220], i_int7220_sender (&out_r), i_uchar7220_sender (&out_mid), unsigned char (&bp)[516], i_uchar7220_sender (&out_image), OSAPI (&os))
    : _specc::behavior(_idcnt), in_image(in_image), out_r(out_r), out_mid(out_mid), bp(bp), out_image(out_image), os(os),
    susan_edges_a(_IDcnt, in_image, r, bp, os),
    susan_edges_b(_IDcnt, in_image, r, mid, bp, os),
    susan_edges_read_input(_IDcnt, r, mid),
    susan_edges_write_output(_IDcnt, out_r, out_mid, out_image, r, mid, in_image)
{   /* nothing */
}

SusanEdges::~SusanEdges(void)
{   /* nothing */
}

#line 362 "susan_edges.sc"
void SusanEdges::main(void) {

    { enum { _scc_state_0, _scc_state_susan_edges_read_input, _scc_state_susan_edges_a, _scc_state_susan_edges_b, _scc_state_susan_edges_write_output } _scc_next_state = _scc_state_susan_edges_read_input; do switch(_scc_next_state) {
	    case _scc_state_susan_edges_read_input: { susan_edges_read_input.main(); { _scc_next_state = _scc_state_susan_edges_a; break; } }
	    case _scc_state_susan_edges_a: { susan_edges_a.main(); { _scc_next_state = _scc_state_susan_edges_b; break; } }
	    case _scc_state_susan_edges_b: { susan_edges_b.main(); { _scc_next_state = _scc_state_susan_edges_write_output; break; } }
	    case _scc_state_susan_edges_write_output: { susan_edges_write_output.main(); { _scc_next_state = _scc_state_0; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
}

#line 2213 "susan_edge_detector.cc"
SusanThinThread::SusanThinThread(unsigned int _idcnt, int (&r)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&os))
    : _specc::behavior(_idcnt), r(r), mid(mid), thID(thID), os(os)
{   /* nothing */
}

SusanThinThread::~SusanThinThread(void)
{   /* nothing */
}

#line 13 "susan_thin.sc"
void SusanThinThread::init(void) {
    task = os.task_create("st_t");
}

void SusanThinThread::main(void) {

    int centre; int l[9];
    int b01; int b10; int b12; int b21;
    int p1; int p2; int p3; int p4;
    int b00; int b02; int b20; int b22;
    int a; int b; int i; int j; int m; int n; int x; int y;
    unsigned char *mp;

    os.task_activate(task);

    for(i = 4 + (95 - 4 - 4) / 2 * thID; i < 4 + (95 - 4 - 4) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 4 - 4) % 2 != 0 ? (95 - 4 - 4) % 2 : 0); i++ ) {


	for(j = 4; j < 76 - 4; j++ )
	    if (mid[i * 76 + j] < 8)
	    {   
		centre = r[i * 76 + j];


		mp = mid + (i - 1) * 76 + j - 1;

		n = ( *mp < 8) + 
		( *(mp + 1) < 8) + 
		( *(mp + 2) < 8) + 
		( *(mp + 76) < 8) + 
		( *(mp + 76 + 2) < 8) + 
		( *(mp + 76 + 76) < 8) + 
		( *(mp + 76 + 76 + 1) < 8) + 
		( *(mp + 76 + 76 + 2) < 8);


		if (n == 0)
		    mid[i * 76 + j] = 100;



		if ((n == 1) && (mid[i * 76 + j] < 6))
		{   

#line 62 "susan_thin.sc"
		    l[0] = r[(i - 1) * 76 + j - 1]; l[1] = r[(i - 1) * 76 + j]; l[2] = r[(i - 1) * 76 + j + 1];
		    l[3] = r[(i) * 76 + j - 1]; l[4] = 0; l[5] = r[(i) * 76 + j + 1];
		    l[6] = r[(i + 1) * 76 + j - 1]; l[7] = r[(i + 1) * 76 + j]; l[8] = r[(i + 1) * 76 + j + 1];

		    if (mid[(i - 1) * 76 + j - 1] < 8) { l[0] = 0; l[1] = 0; l[3] = 0; l[2] *= 2;
			l[6] *= 2; l[5] *= 3; l[7] *= 3; l[8] *= 4;
		    }
		    else 

#line 68 "susan_thin.sc"
		    {    if (mid[(i - 1) * 76 + j] < 8) { l[1] = 0; l[0] = 0; l[2] = 0; l[3] *= 2;
			    l[5] *= 2; l[6] *= 3; l[8] *= 3; l[7] *= 4;
			}
			else 

#line 70 "susan_thin.sc"
			{    if (mid[(i - 1) * 76 + j + 1] < 8) { l[2] = 0; l[1] = 0; l[5] = 0; l[0] *= 2;
				l[8] *= 2; l[3] *= 3; l[7] *= 3; l[6] *= 4;
			    }
			    else 

#line 72 "susan_thin.sc"
			    {    if (mid[(i) * 76 + j - 1] < 8) { l[3] = 0; l[0] = 0; l[6] = 0; l[1] *= 2;
				    l[7] *= 2; l[2] *= 3; l[8] *= 3; l[5] *= 4;
				}
				else 

#line 74 "susan_thin.sc"
				{    if (mid[(i) * 76 + j + 1] < 8) { l[5] = 0; l[2] = 0; l[8] = 0; l[1] *= 2;
					l[7] *= 2; l[0] *= 3; l[6] *= 3; l[3] *= 4;
				    }
				    else 

#line 76 "susan_thin.sc"
				    {    if (mid[(i + 1) * 76 + j - 1] < 8) { l[6] = 0; l[3] = 0; l[7] = 0; l[0] *= 2;
					    l[8] *= 2; l[1] *= 3; l[5] *= 3; l[2] *= 4;
					}
					else 

#line 78 "susan_thin.sc"
					{    if (mid[(i + 1) * 76 + j] < 8) { l[7] = 0; l[6] = 0; l[8] = 0; l[3] *= 2;
						l[5] *= 2; l[0] *= 3; l[2] *= 3; l[1] *= 4;
					    }
					    else 

#line 80 "susan_thin.sc"
					    {    if (mid[(i + 1) * 76 + j + 1] < 8) { l[8] = 0; l[5] = 0; l[7] = 0; l[6] *= 2;
						    l[2] *= 2; l[1] *= 3; l[3] *= 3; l[0] *= 4;
						}
					    }
					}
				    }
				}
			    }
			}
		    }

#line 83 "susan_thin.sc"
		    m = 0;
		    for(y = 0; y < 3; y++ )
			for(x = 0; x < 3; x++ )
			    if (l[y + y + y + x] > m) { m = l[y + y + y + x]; a = y; b = x;
			    }
		    if (m > 0)
		    {   
			if (mid[i * 76 + j] < 4)
			    mid[(i + a - 1) * 76 + j + b - 1] = 4;
			else 
			    mid[(i + a - 1) * 76 + j + b - 1] = mid[i * 76 + j] + 1;
			if ((a + a + b) < 3)
			{   
			    i += a - 1;
			    j += b - 2;
			    if (i < 4) i = 4;
			    if (j < 4) j = 4;
			}
		    }
		}

		if (n == 2)
		{   

		    b00 = mid[(i - 1) * 76 + j - 1] < 8;
		    b02 = mid[(i - 1) * 76 + j + 1] < 8;
		    b20 = mid[(i + 1) * 76 + j - 1] < 8;
		    b22 = mid[(i + 1) * 76 + j + 1] < 8;
		    if (((b00 + b02 + b20 + b22) == 2) && ((b00 | b22) & (b02 | b20)))
		    {   



			if (b00)
			{   
			    if (b02) { x = 0; y =  -1;
			    }
			    else 

#line 119 "susan_thin.sc"
			    {    x =  -1; y = 0;
			    }
			}
			else  {
			    if (b02) { x = 1; y = 0;
			    }
			    else 

#line 124 "susan_thin.sc"
			    {    x = 0; y = 1;
			    }
			} if (((float)r[(i + y) * 76 + j + x] / (float)centre) > 7.000000000000000e-01)
			{   
			    if (((x == 0) && (mid[(i + (2 * y)) * 76 + j] > 7) && (mid[(i + (2 * y)) * 76 + j - 1] > 7) && (mid[(i + (2 * y)) * 76 + j + 1] > 7)) || 
				((y == 0) && (mid[(i) * 76 + j + (2 * x)] > 7) && (mid[(i + 1) * 76 + j + (2 * x)] > 7) && (mid[(i - 1) * 76 + j + (2 * x)] > 7)))
			    {   
				mid[(i) * 76 + j] = 100;
				mid[(i + y) * 76 + j + x] = 3;
			    }
			}
		    }
		    else 
		    {   
			b01 = mid[(i - 1) * 76 + j] < 8;
			b12 = mid[(i) * 76 + j + 1] < 8;
			b21 = mid[(i + 1) * 76 + j] < 8;
			b10 = mid[(i) * 76 + j - 1] < 8;

#line 166 "susan_thin.sc"
			if (((b01 + b12 + b21 + b10) == 2) && ((b10 | b12) & (b01 | b21)) && 
			    ((b01 & ((mid[(i - 2) * 76 + j - 1] < 8) | (mid[(i - 2) * 76 + j + 1] < 8))) | (b10 & ((mid[(i - 1) * 76 + j - 2] < 8) | (mid[(i + 1) * 76 + j - 2] < 8))) | 
				(b12 & ((mid[(i - 1) * 76 + j + 2] < 8) | (mid[(i + 1) * 76 + j + 2] < 8))) | (b21 & ((mid[(i + 2) * 76 + j - 1] < 8) | (mid[(i + 2) * 76 + j + 1] < 8)))))
			{   



			    mid[(i) * 76 + j] = 100;
			    i-- ;
			    j -= 2;
			    if (i < 4) i = 4;
			    if (j < 4) j = 4;
			}
		    }
		}

		if (n > 2)
		{   
		    b01 = mid[(i - 1) * 76 + j] < 8;
		    b12 = mid[(i) * 76 + j + 1] < 8;
		    b21 = mid[(i + 1) * 76 + j] < 8;
		    b10 = mid[(i) * 76 + j - 1] < 8;
		    if ((b01 + b12 + b21 + b10) > 1)
		    {   
			b00 = mid[(i - 1) * 76 + j - 1] < 8;
			b02 = mid[(i - 1) * 76 + j + 1] < 8;
			b20 = mid[(i + 1) * 76 + j - 1] < 8;
			b22 = mid[(i + 1) * 76 + j + 1] < 8;
			p1 = b00 | b01;
			p2 = b02 | b12;
			p3 = b22 | b21;
			p4 = b20 | b10;

			if (((p1 + p2 + p3 + p4) - ((b01 & p2) + (b12 & p3) + (b21 & p4) + (b10 & p1))) < 2)
			{   
			    mid[(i) * 76 + j] = 100;
			    i-- ;
			    j -= 2;
			    if (i < 4) i = 4;
			    if (j < 4) j = 4;
			}
		    }
		}
	    }

	os.time_wait(6400000);
    }
    os.task_terminate();
}

#line 2446 "susan_edge_detector.cc"
SusanThin_ReadInput::SusanThin_ReadInput(unsigned int _idcnt, i_int7220_receiver (&in_r), i_uchar7220_receiver (&in_mid), int (&r)[7220], unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), in_r(in_r), in_mid(in_mid), r(r), mid(mid)
{   /* nothing */
}

SusanThin_ReadInput::~SusanThin_ReadInput(void)
{   /* nothing */
}

#line 220 "susan_thin.sc"
void SusanThin_ReadInput::main(void) {
    in_r.receive( &r);
    in_mid.receive( &mid);
}

#line 2462 "susan_edge_detector.cc"
SusanThin_WriteOutput::SusanThin_WriteOutput(unsigned int _idcnt, i_uchar7220_sender (&out_mid), unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), out_mid(out_mid), mid(mid)
{   /* nothing */
}

SusanThin_WriteOutput::~SusanThin_WriteOutput(void)
{   /* nothing */
}

#line 228 "susan_thin.sc"
void SusanThin_WriteOutput::main(void) {
    out_mid.send(mid);
}

#line 2477 "susan_edge_detector.cc"
SusanThin::SusanThin(unsigned int _idcnt, int (&r)[7220], unsigned char (&mid)[7220], OSAPI (&os))
    : _specc::behavior(_idcnt), r(r), mid(mid), os(os),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    susan_thin_thread_0(_IDcnt, r, mid, _scc_const_port_0, os),
    susan_thin_thread_1(_IDcnt, r, mid, _scc_const_port_1, os)
{   /* nothing */
}

SusanThin::~SusanThin(void)
{   /* nothing */
}

#line 240 "susan_thin.sc"
void SusanThin::main(void) {

    susan_thin_thread_0.init();
    susan_thin_thread_1.init();

    task = os.par_start();
    { _specc::fork _scc_fork_0(&susan_thin_thread_0), _scc_fork_1(&susan_thin_thread_1); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, ((_specc::fork*)0));
    }
    os.par_end(task);
}

#line 2505 "susan_edge_detector.cc"
Thin::Thin(unsigned int _idcnt, i_int7220_receiver (&in_r), i_uchar7220_receiver (&in_mid), i_uchar7220_sender (&out_mid), OSAPI (&os))
    : _specc::behavior(_idcnt), in_r(in_r), in_mid(in_mid), out_mid(out_mid), os(os),
    susan_thin(_IDcnt, r, mid, os),
    susan_thin_read_input(_IDcnt, in_r, in_mid, r, mid),
    susan_thin_write_output(_IDcnt, out_mid, mid)
{   /* nothing */
}

Thin::~Thin(void)
{   /* nothing */
}

#line 266 "susan_thin.sc"
void Thin::init(void) {
    task = os.task_create("thin");
}

void Thin::main(void) {
    os.task_activate(task);
    { enum { _scc_state_0, _scc_state_susan_thin_read_input, _scc_state_susan_thin, _scc_state_susan_thin_write_output } _scc_next_state = _scc_state_susan_thin_read_input; do switch(_scc_next_state) {
	    case _scc_state_susan_thin_read_input: { susan_thin_read_input.main(); { _scc_next_state = _scc_state_susan_thin; break; } }
	    case _scc_state_susan_thin: { susan_thin.main(); { _scc_next_state = _scc_state_susan_thin_write_output; break; } }
	    case _scc_state_susan_thin_write_output: { susan_thin_write_output.main(); { _scc_next_state = _scc_state_susan_thin_read_input; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
    os.task_terminate();
}

#line 2533 "susan_edge_detector.cc"
WriteImage::WriteImage(unsigned int _idcnt, i_sender (&out_image), slave_receiver (&in_image))
    : _specc::behavior(_idcnt), out_image(out_image), in_image(in_image)
{   /* nothing */
}

WriteImage::~WriteImage(void)
{   /* nothing */
}

#line 11 "write_image.sc"
void WriteImage::main(void) {

    unsigned char image_buffer[7220];

    while(true) {

	in_image.receive(image_buffer);
	out_image.send(image_buffer, sizeof (image_buffer));
    }
}

#line 2555 "susan_edge_detector.cc"
void _scc_bit4_err_handle(
    const _bit4& bit4vec)
{   
    char temp_bits[1024], *p;
    p=bit2str(2,&temp_bits[1023], bit4vec);
    _specc::abort(
	"ERROR:\t Casting a bit4 vector failed \n"
	"Bit4 vector contains X/Z values %s\n"
	"Simulation aborted.\n", p);
	
}

//////////////////////////////////////////////////////////////////////
// End of file susan_edge_detector.cc
//////////////////////////////////////////////////////////////////////
