//////////////////////////////////////////////////////////////////////
// C++ source file generated by SpecC V2.2.1
// Design: susan_edge_detector
// File:   susan_edge_detector.cc
// Time:   Tue Oct 27 18:05:31 2015
//////////////////////////////////////////////////////////////////////

// Note: User-defined include files are inlined in this file.

// Note: System-defined include files are inlined in this file.

#include "susan_edge_detector.h"


unsigned int _IDcnt = 0;
// channel class definitions /////////////////////////////////////////

c_double_handshake_signal::c_double_handshake_signal()
    : _specc::channel(),
    v(false),
    w(false)
{   /* nothing */
}

c_double_handshake_signal::~c_double_handshake_signal(void)
{   /* nothing */
}

#line 14 "./c_double_handshake_signal.sc"
void c_double_handshake_signal::receive(void)
{   
    if ( !v)
    {   
	w = true;
	_specc::wait(event(&req), ((void*)0));
	w = false;
    }
    v = false;
    _specc::notify(event(&ack), ((void*)0));
    _specc::wait(event(&ack), ((void*)0));
}

void c_double_handshake_signal::send(void)
{   
    v = true;
    if (w)
    {   
	_specc::notify(event(&req), ((void*)0));
    }
    _specc::wait(event(&ack), ((void*)0));
}

#line 54 "susan_edge_detector.cc"
OS::OS()
    : _specc::channel(),
    head(0),
    start(0u),
    tail(0),
    task_pool(1u),
    e0(),
    e1(),
    e10(),
    e11(),
    e12(),
    e13(),
    e14(),
    e15(),
    e16(),
    e17(),
    e18(),
    e19(),
    e2(),
    e3(),
    e4(),
    e5(),
    e6(),
    e7(),
    e8(),
    e9()
{   /* nothing */
}

OS::~OS(void)
{   /* nothing */
}

#line 127 "./os.sc"
void OS::dispatch(void) {
    unsigned int position;


    position = head;
    current = pop_t();
    printf("current.id = %d\n", current.id);
    if (current.id != 0)
    {   

	switch(position) {
	    case 0:
		e0.send();
	    printf("e0 send\n");
	    break;
	    case 1:
		e1.send();
	    printf("e1 send\n");
	    break;
	    case 2:
		e2.send();
	    printf("e2 send\n");
	    break;
	    case 3:
		e3.send();
	    printf("e3 send\n");
	    break;
	    case 4:
		e4.send();
	    printf("e4 send\n");
	    break;
	    case 5:
		e5.send();
	    printf("e5 send\n");
	    break;
	    case 6:
		e6.send();
	    printf("e6 send\n");
	    break;
	    case 7:
		e7.send();
	    printf("e7 send\n");
	    break;
	    case 8:
		e8.send();
	    printf("e8 send\n");
	    break;
	    case 9:
		e9.send();
	    printf("e9 send\n");
	    break;
	    case 10:
		e10.send();
	    printf("e10 send\n");
	    break;
	    case 11:
		e11.send();
	    printf("e11 send\n");
	    break;
	    case 12:
		e12.send();
	    printf("e12 send\n");
	    break;
	    case 13:
		e13.send();
	    printf("e13 send\n");
	    break;
	    case 14:
		e14.send();
	    printf("e14 send\n");
	    break;
	    case 15:
		e15.send();
	    printf("e15 send\n");
	    break;
	    case 16:
		e16.send();
	    printf("e16 send\n");
	    break;
	    case 17:
		e17.send();
	    printf("e17 send\n");
	    break;
	    case 18:
		e18.send();
	    printf("e18 send\n");
	    break;
	    case 19:
		e19.send();
	    printf("e19 send\n");
	    break;
	}
    }
}

#line 709 "./os.sc"
void OS::init(struct Task t) {
    current = t;
}

#line 612 "./os.sc"
void OS::par_end(struct Task t) {
    int position;
    if (head == tail && start == 0)
	current = t;
    else  {
	push_t(current);
	current = t;
	position = tail - 1;
	switch(position) {
	    case 0:
		printf("par end : e0 wait here\n");
	    e0.receive();
	    break;
	    case 1:
		printf("par end :e1 wait here\n");
	    e1.receive();
	    break;
	    case 2:
		printf("par end :e2 wait here\n");
	    e2.receive();
	    break;
	    case 3:
		printf("par end :e3 wait here\n");
	    e3.receive();
	    break;
	    case 4:
		printf("par end :e4 wait here\n");
	    e4.receive();
	    break;
	    case 5:
		printf("par end :e5 wait here\n");
	    e5.receive();
	    break;
	    case 6:
		printf("par end :e6 wait here\n");
	    e6.receive();
	    break;
	    case 7:
		printf("par end :e7 wait here\n");
	    e7.receive();
	    break;
	    case 8:
		printf("par end :e8 wait here\n");
	    e8.receive();
	    break;
	    case 9:
		printf("par end :e9 wait here\n");
	    e9.receive();
	    break;
	    case 10:
		printf("par end :e10 wait here\n");
	    e10.receive();
	    break;
	    case 11:
		printf("par end :e11 wait here\n");
	    e11.receive();
	    break;
	    case 12:
		printf("par end :e12 wait here\n");
	    e12.receive();
	    break;
	    case 13:
		printf("par end :e13 wait here\n");
	    e13.receive();
	    break;
	    case 14:
		printf("par end :e14 wait here\n");
	    e14.receive();
	    break;
	    case 15:
		printf("par end :e15 wait here\n");
	    e15.receive();
	    break;
	    case 16:
		printf("par end :e16 wait here\n");
	    e16.receive();
	    break;
	    case 17:
		printf("par end :e17 wait here\n");
	    e17.receive();
	    break;
	    case 18:
		printf("par end :e18 wait here\n");
	    e18.receive();
	    break;
	    case 19:
		printf("par end :e19 wait here\n");
	    e19.receive();
	    break;
	    default:
		break;
	}
    }

    return ;
}

#line 599 "./os.sc"
struct Task OS::par_start(void) {
    struct Task ret_t;
    ret_t = current;

    if ((head == tail) && (start == 0))
	printf("empty queue before par start\n");
    else  {
	dispatch();
    }
    printf("par start, current id is %d\n", ret_t.id);
    return ret_t;
}

#line 91 "./os.sc"
struct Task OS::pop_t(void) {
    struct Task t;
    if ((head == tail) && (start == 0)) {
	printf("queue is empty\n");
	exit(0);
    }
    else  {
	t = rdyq[head];
	printf("pop id is %d\n", t.id);
	head = (head + 1) % 20;
	if (start == 1)
	    start = 0;
	return t;
    }
}

#line 488 "./os.sc"
void OS::post_wait(struct Task t) {

    int position;

    printf("start post wait\n");
    printf("id of task is %d\n", t.id);
    printf("is start equals to %d\n", start);

    if (head == tail && start == 0) {
	push_t(t);
    }
    else  {
	push_t(t);
	if (tail == 0) {
	    position = 19;
	}
	else 

#line 503 "./os.sc"
	{   
	    position = tail - 1;
	}
	switch(position) {
	    case 0:
		printf("post_wait : e0 wait here\n");
	    e0.receive();
	    break;
	    case 1:
		printf("post_wait :e1 wait here\n");
	    e1.receive();
	    break;
	    case 2:
		printf("post_wait :e2 wait here\n");
	    e2.receive();
	    break;
	    case 3:
		printf("post_wait :e3 wait here\n");
	    e3.receive();
	    break;
	    case 4:
		printf("post_wait :e4 wait here\n");
	    e4.receive();
	    break;
	    case 5:
		printf("post_wait :e5 wait here\n");
	    e5.receive();
	    break;
	    case 6:
		printf("post_wait :e6 wait here\n");
	    e6.receive();
	    break;
	    case 7:
		printf("post_wait :e7 wait here\n");
	    e7.receive();
	    break;
	    case 8:
		printf("post_wait :e8 wait here\n");
	    e8.receive();
	    break;
	    case 9:
		printf("post_wait :e9 wait here\n");
	    e9.receive();
	    break;
	    case 10:
		printf("post_wait :e10 wait here\n");
	    e10.receive();
	    break;
	    case 11:
		printf("post_wait :e11 wait here\n");
	    e11.receive();
	    break;
	    case 12:
		printf("post_wait :e12 wait here\n");
	    e12.receive();
	    break;
	    case 13:
		printf("post_wait :e13 wait here\n");
	    e13.receive();
	    break;
	    case 14:
		printf("post_wait :e14 wait here\n");
	    e14.receive();
	    break;
	    case 15:
		printf("post_wait :e15 wait here\n");
	    e15.receive();
	    break;
	    case 16:
		printf("post_wait :e16 wait here\n");
	    e16.receive();
	    break;
	    case 17:
		printf("post_wait :e17 wait here\n");
	    e17.receive();
	    break;
	    case 18:
		printf("e18 wait here\n");
	    e18.receive();
	    break;
	    case 19:
		printf("e19 wait here\n");
	    e19.receive();
	    break;
	    default:
		break;
	}
    }
}

#line 473 "./os.sc"
struct Task OS::pre_wait() {
    struct Task t;

    t = current;
    printf("pre wait, current id is %d, head is %d, tail is %d\n", t.id, head, tail);
    if (head == tail && start == 0) {
	printf("pre_wait queue empty nothing to dispath\n");
    }
    else 

#line 480 "./os.sc"
    {   
	if (head == 8)
	    printf("MAYBE WRONG HERE");
	dispatch();
    }
    return t;
}

#line 61 "./os.sc"
void OS::push_t(struct Task t) {

    if (start == 1) {
	printf("queue is full\n");
	exit(0);
    }
    printf("push %d\n", t.id);
    rdyq[tail] = t;
    tail = (tail + 1) % 20;
    if (tail == head)
	start = 1;
    return ;
}

#line 221 "./os.sc"
void OS::task_activate(struct Task t) {
    unsigned int position;
    unsigned int i;
    i = head;
    while((i >= head) || (i <= tail)) {
	if (rdyq[i].id == t.id) {
	    position = i;
	    break;
	}
	else  {
	    if (i == 19)
		i = 0;
	    else 
		i = i + 1;
	}
    }
    switch(position) {
	case 0:
	    e0.receive();
	break;
	case 1:
	    e1.receive();
	break;
	case 2:
	    e2.receive();
	break;
	case 3:
	    e3.receive();
	break;
	case 4:
	    e4.receive();
	break;
	case 5:
	    e5.receive();
	break;
	case 6:
	    e6.receive();
	break;
	case 7:
	    e7.receive();
	break;
	case 8:
	    e8.receive();
	break;
	case 9:
	    e9.receive();
	break;
	case 10:
	    e10.receive();
	break;
	case 11:
	    e11.receive();
	break;
	case 12:
	    e12.receive();
	break;
	case 13:
	    e13.receive();
	break;
	case 14:
	    e14.receive();
	break;
	case 15:
	    e15.receive();
	break;
	case 16:
	    e16.receive();
	break;
	case 17:
	    e17.receive();
	break;
	case 18:
	    e18.receive();
	break;
	case 19:
	    e19.receive();
	break;
	default:
	    break;
    }
}

#line 47 "./os.sc"
struct Task OS::task_create(char *a) {

    if (a != "") {
	struct Task new_id;
	new_id.id = task_pool;
	task_pool = task_pool + 1;
	printf("name is %s and id is %d\n", a, new_id.id);
	return new_id;
    }
    else  {
	printf("Wrong task name");
    }
}

#line 302 "./os.sc"
void OS::task_terminate(void) {



    if ( !(head == tail && start == 0)) {

	printf("TERMINATION head %d tail %d \n", head, tail);
	printf("current id is %d\n", current.id);
	if (head == 8)
	    printf("MAYBE WRONG HERE");
	dispatch();
	printf("my head %d tail %d \n", head, tail);
    }
    else  {
	printf("TERMINATION head %d tail %d!!!\n", head, tail);
    }
}

#line 593 "./os.sc"
void OS::time_wait(unsigned int t) {
    _specc::waitfor((t));
    printf("time to wait %d\n", t);
    yield();
}

#line 319 "./os.sc"
void OS::yield(void) {
    unsigned int position;
    unsigned int flag; unsigned int i;
    struct Task t;
    t = current;

    push_t(t);
    printf("YIELD dispatch \n");
    if (head == 8)
	printf("MAYBE WRONG HERE");
    dispatch();

    position = ((tail - 1) >= 0 ? (tail - 1) : (tail - 1 + 20));


    printf("head is %d ; tail is %d ;  position is %d\n", head, tail, position);

    printf("ready queue: \n");
    i = head;
    while(i != tail) {
	printf("%d:%d ", i, rdyq[i].id);
	i = (i + 1) % 20;
    }

    switch(position) {
	case 0:
	    printf("e0 wait here\n");
	e0.receive();
	break;
	case 1:
	    printf("e1 wait here\n");
	e1.receive();
	break;
	case 2:
	    printf("e2 wait here\n");
	e2.receive();
	break;
	case 3:
	    printf("e3 wait here\n");
	e3.receive();
	break;
	case 4:
	    printf("e4 wait here\n");
	e4.receive();
	break;
	case 5:
	    printf("e5 wait here\n");
	e5.receive();
	break;
	case 6:
	    printf("e6 wait here\n");
	e6.receive();
	break;
	case 7:
	    printf("e7 wait here\n");
	e7.receive();
	break;
	case 8:
	    printf("e8 wait here\n");
	e8.receive();
	break;
	case 9:
	    printf("e9 wait here\n");
	e9.receive();
	break;
	case 10:
	    printf("e10 wait here\n");
	e10.receive();
	break;
	case 11:
	    printf("e11 wait here\n");
	e11.receive();
	break;
	case 12:
	    printf("e12 wait here\n");
	e12.receive();
	break;
	case 13:
	    printf("e13 wait here\n");
	e13.receive();
	break;
	case 14:
	    printf("e14 wait here\n");
	e14.receive();
	break;
	case 15:
	    printf("e15 wait here\n");
	e15.receive();
	break;
	case 16:
	    printf("e16 wait here\n");
	e16.receive();
	break;
	case 17:
	    printf("e17 wait here\n");
	e17.receive();
	break;
	case 18:
	    printf("e18 wait here\n");
	e18.receive();
	break;
	case 19:
	    printf("e19 wait here\n");
	e19.receive();
	break;
	default:
	    break;
    }
}

#line 698 "susan_edge_detector.cc"
c_double_handshake::c_double_handshake()
    : _specc::channel(),
    v(false),
    w(false)
{   /* nothing */
}

c_double_handshake::~c_double_handshake(void)
{   /* nothing */
}

#line 81 "c_double_handshake.sc"
void c_double_handshake::receive(void *d, unsigned long int l)
{   
    if ( !v)
    {   
	w = true;
	_specc::wait(event(&req), ((void*)0));
	w = false;
    }
    if (l != tmpl)
    {   
	abort();
    }
    memcpy(d, tmpd, l);
    v = false;
    _specc::notify(event(&ack), ((void*)0));
    _specc::wait(event(&ack), ((void*)0));
}

void c_double_handshake::send(const void *d, unsigned long int l)
{   
    tmpd = d;
    tmpl = l;
    v = true;
    if (w)
    {   
	_specc::notify(event(&req), ((void*)0));
    }
    _specc::wait(event(&ack), ((void*)0));
}

#line 741 "susan_edge_detector.cc"
c_handshake::c_handshake()
    : _specc::channel(),
    f(false),
    w(false)
{   /* nothing */
}

c_handshake::~c_handshake(void)
{   /* nothing */
}

#line 62 "c_handshake.sc"
void c_handshake::receive(void)
{   
    if ( !f)
    {   
	w = true;
	_specc::wait(event(&e), ((void*)0));
	w = false;
    }
    f = false;
}

void c_handshake::send(void)
{   
    if (w)
    {   
	_specc::notify(event(&e), ((void*)0));
    }
    f = true;
}

#line 774 "susan_edge_detector.cc"
c_int7220r_queue::c_int7220r_queue(const unsigned long int (&size), OSAPI (&rtos))
    : _specc::channel(), size(size), rtos(rtos),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_int7220r_queue::~c_int7220r_queue(void)
{   /* nothing */
}

#line 9 "c_int7220_queue_r.sc"
void c_int7220r_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 9 "c_int7220_queue_r.sc"
void c_int7220r_queue::receive(int (*d)[7220]) { struct Task t; while( !n) { wr++ ; t = rtos.pre_wait(); _specc::wait(event(&r), ((void*)0)); printf("receive post wait \n"); rtos.post_wait(t); wr-- ;
    }

#line 9 "c_int7220_queue_r.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 9 "c_int7220_queue_r.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 9 "c_int7220_queue_r.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 9 "c_int7220_queue_r.sc"
    cleanup();
}

#line 9 "c_int7220_queue_r.sc"
void c_int7220r_queue::send(int d[7220]) { while(n >= size) { ws++ ; _specc::wait(event(&s), ((void*)0)); ws-- ;
    }

#line 9 "c_int7220_queue_r.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 9 "c_int7220_queue_r.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 9 "c_int7220_queue_r.sc"
void c_int7220r_queue::setup(void) { if ( !buffer) { int dummy[7220]; unsigned long int i; if ( !(buffer = (int (*)[7220])malloc(sizeof(int [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 9 "c_int7220_queue_r.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(int [7220]));
	}
    }
}

#line 838 "susan_edge_detector.cc"
c_int7220s_queue::c_int7220s_queue(const unsigned long int (&size), OSAPI (&rtos))
    : _specc::channel(), size(size), rtos(rtos),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_int7220s_queue::~c_int7220s_queue(void)
{   /* nothing */
}

#line 9 "c_int7220_queue_s.sc"
void c_int7220s_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 9 "c_int7220_queue_s.sc"
void c_int7220s_queue::receive(int (*d)[7220]) { while( !n) { wr++ ; _specc::wait(event(&r), ((void*)0)); wr-- ;
    }

#line 9 "c_int7220_queue_s.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 9 "c_int7220_queue_s.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 9 "c_int7220_queue_s.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 9 "c_int7220_queue_s.sc"
    cleanup();
}

#line 9 "c_int7220_queue_s.sc"
void c_int7220s_queue::send(int d[7220]) { struct Task t; while(n >= size) { ws++ ; t = rtos.pre_wait(); _specc::wait(event(&s), ((void*)0)); printf("send post wait \n"); rtos.post_wait(t); ws-- ;
    }

#line 9 "c_int7220_queue_s.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 9 "c_int7220_queue_s.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 9 "c_int7220_queue_s.sc"
void c_int7220s_queue::setup(void) { if ( !buffer) { int dummy[7220]; unsigned long int i; if ( !(buffer = (int (*)[7220])malloc(sizeof(int [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 9 "c_int7220_queue_s.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(int [7220]));
	}
    }
}

#line 902 "susan_edge_detector.cc"
c_int7220sr_queue::c_int7220sr_queue(const unsigned long int (&size), OSAPI (&rtos))
    : _specc::channel(), size(size), rtos(rtos),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_int7220sr_queue::~c_int7220sr_queue(void)
{   /* nothing */
}

#line 9 "c_int7220_queue_sr.sc"
void c_int7220sr_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 9 "c_int7220_queue_sr.sc"
void c_int7220sr_queue::receive(int (*d)[7220]) { struct Task t; while( !n) { wr++ ; t = rtos.pre_wait(); printf("pre_wait id is %d\n", t.id); _specc::wait(event(&r), ((void*)0)); printf("receive post wait\n"); rtos.post_wait(t); wr-- ;
    }

#line 9 "c_int7220_queue_sr.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 9 "c_int7220_queue_sr.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 9 "c_int7220_queue_sr.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 9 "c_int7220_queue_sr.sc"
    cleanup();
}

#line 9 "c_int7220_queue_sr.sc"
void c_int7220sr_queue::send(int d[7220]) { struct Task t; while(n >= size) { ws++ ; t = rtos.pre_wait(); printf("pre_wait id is %d\n", t.id); _specc::wait(event(&s), ((void*)0)); printf("send post wait\n"); rtos.post_wait(t); ws-- ;
    }

#line 9 "c_int7220_queue_sr.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 9 "c_int7220_queue_sr.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 9 "c_int7220_queue_sr.sc"
void c_int7220sr_queue::setup(void) { if ( !buffer) { int dummy[7220]; unsigned long int i; if ( !(buffer = (int (*)[7220])malloc(sizeof(int [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 9 "c_int7220_queue_sr.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(int [7220]));
	}
    }
}

#line 966 "susan_edge_detector.cc"
c_queue::c_queue(const unsigned long int (&size))
    : _specc::channel(), size(size),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_queue::~c_queue(void)
{   /* nothing */
}

#line 99 "c_queue.sc"
void c_queue::cleanup(void)
{   
    if ( !n)
    {   
	free(buffer);
	buffer = 0;
    }
}

void c_queue::receive(void *d, unsigned long int l)
{   
    unsigned long int p0;

    while(l > n)
    {   
	wr++ ;
	_specc::wait(event(&r), ((void*)0));
	wr-- ;
    }

    if (n <= p)
    {   
	p0 = p - n;
    }
    else 
    {   
	p0 = p + size - n;
    }
    if (l <= size - p0)
    {   
	memcpy(d,  &buffer[p0], l);
	n -= l;
    }
    else 
    {   
	memcpy(d,  &buffer[p0], size - p0);
	memcpy(((char *)d) + (size - p0),  &buffer[0], l - (size - p0));
	n -= l;
    }

    if (ws)
    {   
	_specc::notify(event(&s), ((void*)0));
    }

    cleanup();
}

void c_queue::send(const void *d, unsigned long int l)
{   
    while(l > size - n)
    {   
	ws++ ;
	_specc::wait(event(&s), ((void*)0));
	ws-- ;
    }

    setup();

    if (l <= size - p)
    {   
	memcpy( &buffer[p], d, l);
	p += l;
	n += l;
    }
    else 
    {   
	memcpy( &buffer[p], d, size - p);
	memcpy( &buffer[0], ((char *)d) + (size - p), l - (size - p));
	p = l - (size - p);
	n += l;
    }

    if (wr)
    {   
	_specc::notify(event(&r), ((void*)0));
    }
}

#line 87 "c_queue.sc"
void c_queue::setup(void)
{   
    if ( !buffer)
    {   
	if ( !(buffer = (char *)malloc(size)))
	{   
	    perror("c_queue");
	    abort();
	}
    }
}

#line 1074 "susan_edge_detector.cc"
c_uchar7220_queue::c_uchar7220_queue(const unsigned long int (&size))
    : _specc::channel(), size(size),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_uchar7220_queue::~c_uchar7220_queue(void)
{   /* nothing */
}

#line 8 "c_uchar7220_queue.sc"
void c_uchar7220_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 8 "c_uchar7220_queue.sc"
void c_uchar7220_queue::receive(unsigned char (*d)[7220]) { while( !n) { wr++ ; _specc::wait(event(&r), ((void*)0)); wr-- ;
    }

#line 8 "c_uchar7220_queue.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 8 "c_uchar7220_queue.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 8 "c_uchar7220_queue.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 8 "c_uchar7220_queue.sc"
    cleanup();
}

#line 8 "c_uchar7220_queue.sc"
void c_uchar7220_queue::send(unsigned char d[7220]) { while(n >= size) { ws++ ; _specc::wait(event(&s), ((void*)0)); ws-- ;
    }

#line 8 "c_uchar7220_queue.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 8 "c_uchar7220_queue.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 8 "c_uchar7220_queue.sc"
void c_uchar7220_queue::setup(void) { if ( !buffer) { unsigned char dummy[7220]; unsigned long int i; if ( !(buffer = (unsigned char (*)[7220])malloc(sizeof(unsigned char [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 8 "c_uchar7220_queue.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [7220]));
	}
    }
}

#line 1138 "susan_edge_detector.cc"
c_uchar7220r_queue::c_uchar7220r_queue(const unsigned long int (&size), OSAPI (&rtos))
    : _specc::channel(), size(size), rtos(rtos),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_uchar7220r_queue::~c_uchar7220r_queue(void)
{   /* nothing */
}

#line 8 "c_uchar7220_queue_r.sc"
void c_uchar7220r_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 8 "c_uchar7220_queue_r.sc"
void c_uchar7220r_queue::receive(unsigned char (*d)[7220]) { struct Task t; while( !n) { wr++ ; t = rtos.pre_wait(); _specc::wait(event(&r), ((void*)0)); printf("receive post wait \n"); rtos.post_wait(t); wr-- ;
    }

#line 8 "c_uchar7220_queue_r.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 8 "c_uchar7220_queue_r.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 8 "c_uchar7220_queue_r.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 8 "c_uchar7220_queue_r.sc"
    cleanup();
}

#line 8 "c_uchar7220_queue_r.sc"
void c_uchar7220r_queue::send(unsigned char d[7220]) { while(n >= size) { ws++ ; _specc::wait(event(&s), ((void*)0)); ws-- ;
    }

#line 8 "c_uchar7220_queue_r.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 8 "c_uchar7220_queue_r.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 8 "c_uchar7220_queue_r.sc"
void c_uchar7220r_queue::setup(void) { if ( !buffer) { unsigned char dummy[7220]; unsigned long int i; if ( !(buffer = (unsigned char (*)[7220])malloc(sizeof(unsigned char [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 8 "c_uchar7220_queue_r.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [7220]));
	}
    }
}

#line 1202 "susan_edge_detector.cc"
c_uchar7220s_queue::c_uchar7220s_queue(const unsigned long int (&size), OSAPI (&rtos))
    : _specc::channel(), size(size), rtos(rtos),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_uchar7220s_queue::~c_uchar7220s_queue(void)
{   /* nothing */
}

#line 9 "c_uchar7220_queue_s.sc"
void c_uchar7220s_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 9 "c_uchar7220_queue_s.sc"
void c_uchar7220s_queue::receive(unsigned char (*d)[7220]) { while( !n) { wr++ ; _specc::wait(event(&r), ((void*)0)); wr-- ;
    }

#line 9 "c_uchar7220_queue_s.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 9 "c_uchar7220_queue_s.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 9 "c_uchar7220_queue_s.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 9 "c_uchar7220_queue_s.sc"
    cleanup();
}

#line 9 "c_uchar7220_queue_s.sc"
void c_uchar7220s_queue::send(unsigned char d[7220]) { struct Task t; while(n >= size) { ws++ ; t = rtos.pre_wait(); _specc::wait(event(&s), ((void*)0)); printf("send post wait \n"); rtos.post_wait(t); ws-- ;
    }

#line 9 "c_uchar7220_queue_s.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 9 "c_uchar7220_queue_s.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 9 "c_uchar7220_queue_s.sc"
void c_uchar7220s_queue::setup(void) { if ( !buffer) { unsigned char dummy[7220]; unsigned long int i; if ( !(buffer = (unsigned char (*)[7220])malloc(sizeof(unsigned char [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 9 "c_uchar7220_queue_s.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [7220]));
	}
    }
}

#line 1266 "susan_edge_detector.cc"
c_uchar7220sr_queue::c_uchar7220sr_queue(const unsigned long int (&size), OSAPI (&rtos))
    : _specc::channel(), size(size), rtos(rtos),
    buffer(0),
    n(0ul),
    p(0ul),
    wr(0ul),
    ws(0ul)
{   /* nothing */
}

c_uchar7220sr_queue::~c_uchar7220sr_queue(void)
{   /* nothing */
}

#line 9 "c_uchar7220_queue_sr.sc"
void c_uchar7220sr_queue::cleanup(void) { if ( !n) { free(buffer); buffer = 0;
    }
}

#line 9 "c_uchar7220_queue_sr.sc"
void c_uchar7220sr_queue::receive(unsigned char (*d)[7220]) { struct Task t; while( !n) { wr++ ; t = rtos.pre_wait(); printf("pre_wait id is %d\n", t.id); _specc::wait(event(&r), ((void*)0)); printf("receive post wait\n"); rtos.post_wait(t); wr-- ;
    }

#line 9 "c_uchar7220_queue_sr.sc"
    if (n <= p) { { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p - n])[_scc_index_0]; }
    }
    else 

#line 9 "c_uchar7220_queue_sr.sc"
    {    { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) ( *d)[_scc_index_0] = (buffer[p + size - n])[_scc_index_0]; }
    }

#line 9 "c_uchar7220_queue_sr.sc"
    n-- ; if (ws) { _specc::notify(event(&s), ((void*)0));
    }

#line 9 "c_uchar7220_queue_sr.sc"
    cleanup();
}

#line 9 "c_uchar7220_queue_sr.sc"
void c_uchar7220sr_queue::send(unsigned char d[7220]) { struct Task t; while(n >= size) { ws++ ; t = rtos.pre_wait(); printf("pre_wait id is %d\n", t.id); _specc::wait(event(&s), ((void*)0)); printf("send post wait\n"); rtos.post_wait(t); ws-- ;
    }

#line 9 "c_uchar7220_queue_sr.sc"
    setup(); { unsigned int _scc_index_0; for(_scc_index_0=0;_scc_index_0<7220;_scc_index_0++) (buffer[p])[_scc_index_0] = (d)[_scc_index_0]; } p++ ; if (p >= size) { p = 0;
    }

#line 9 "c_uchar7220_queue_sr.sc"
    n++ ; if (wr) { _specc::notify(event(&r), ((void*)0));
    }
}

#line 9 "c_uchar7220_queue_sr.sc"
void c_uchar7220sr_queue::setup(void) { if ( !buffer) { unsigned char dummy[7220]; unsigned long int i; if ( !(buffer = (unsigned char (*)[7220])malloc(sizeof(unsigned char [7220]) * size))) { perror("c_typed_queue"); abort();
	}

#line 9 "c_uchar7220_queue_sr.sc"
	for(i = 0; i < size; i++ ) { memcpy( &buffer[i],  &dummy, sizeof(unsigned char [7220]));
	}
    }
}

// behavior class definitions ////////////////////////////////////////

#line 1332 "susan_edge_detector.cc"
ReadImage_wp::ReadImage_wp(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], i_uchar7220r_sender (&out_image))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), out_image(out_image),
    R(_IDcnt, start, image_buffer, out_image)
{   /* nothing */
}

ReadImage_wp::~ReadImage_wp(void)
{   /* nothing */
}

#line 12 "design.sc"
void ReadImage_wp::main(void) {
    { enum { _scc_state_0, _scc_state_R } _scc_next_state = _scc_state_R; do switch(_scc_next_state) {
	    case _scc_state_R: { R.main(); { _scc_next_state = _scc_state_R; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
}

#line 1350 "susan_edge_detector.cc"
WriteImage_wp::WriteImage_wp(unsigned int _idcnt, i_uchar7220s_receiver (&in_image), i_sender (&out_image))
    : _specc::behavior(_idcnt), in_image(in_image), out_image(out_image),
    W(_IDcnt, in_image, out_image)
{   /* nothing */
}

WriteImage_wp::~WriteImage_wp(void)
{   /* nothing */
}

#line 23 "design.sc"
void WriteImage_wp::main(void) {
    { enum { _scc_state_0, _scc_state_W } _scc_next_state = _scc_state_W; do switch(_scc_next_state) {
	    case _scc_state_W: { W.main(); { _scc_next_state = _scc_state_W; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
}

#line 1368 "susan_edge_detector.cc"
Design::Design(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], i_sender (&out_image_susan))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), out_image_susan(out_image_susan),
    _scc_const_port_0(1ul),
    _scc_const_port_1(1ul),
    in_image(_scc_const_port_0, rtos),
    out_image(_scc_const_port_1, rtos),
    pe1(++_IDcnt, in_image, out_image, rtos),
    read_image(++_IDcnt, start, image_buffer, in_image),
    rtos(),
    write_image(++_IDcnt, out_image, out_image_susan)
{   /* nothing */
}

Design::~Design(void)
{   /* nothing */
}

#line 46 "design.sc"
void Design::main(void) {
    { _specc::fork _scc_fork_0(&read_image), _scc_fork_1(&pe1), _scc_fork_2(&write_image); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 

	    &_scc_fork_2, ((_specc::fork*)0));
    }
}

#line 1396 "susan_edge_detector.cc"
DetectEdges::DetectEdges(unsigned int _idcnt, i_uchar7220r_receiver (&in_image), i_int7220sr_sender (&out_r), i_uchar7220sr_sender (&out_mid), i_uchar7220sr_sender (&out_image), OSAPI (&rtos))
    : _specc::behavior(_idcnt), in_image(in_image), out_r(out_r), out_mid(out_mid), out_image(out_image), rtos(rtos),
    setup_brightness_lut(_IDcnt, bp, rtos),
    susan_edges(_IDcnt, in_image, out_r, out_mid, bp, out_image, rtos)
{   /* nothing */
}

DetectEdges::~DetectEdges(void)
{   /* nothing */
}

#line 23 "detect_edges.sc"
void DetectEdges::main(void) {
    setup_brightness_lut.main();
    susan_edges.main();
}

#line 1414 "susan_edge_detector.cc"
Edges::Edges(unsigned int _idcnt, i_uchar7220r_receiver (&in_image), i_int7220sr_sender (&out_r), i_uchar7220sr_sender (&out_mid), i_uchar7220sr_sender (&out_image), OSAPI (&rtos))
    : _specc::behavior(_idcnt), in_image(in_image), out_r(out_r), out_mid(out_mid), out_image(out_image), rtos(rtos),
    detect_edges(_IDcnt, in_image, out_r, out_mid, out_image, rtos)
{   /* nothing */
}

Edges::~Edges(void)
{   /* nothing */
}

#line 38 "detect_edges.sc"
void Edges::init(void) {
    task = rtos.task_create("EDGES");
    rtos.push_t(task);
    return ;
}

void Edges::main(void) {

    rtos.task_activate(task);

    { enum { _scc_state_0, _scc_state_detect_edges } _scc_next_state = _scc_state_detect_edges; do switch(_scc_next_state) {
	    case _scc_state_detect_edges: { detect_edges.main(); { _scc_next_state = _scc_state_detect_edges; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
    printf("escape fsm of detect edges\n");
    rtos.task_terminate();
}

#line 1443 "susan_edge_detector.cc"
EdgeDrawThread_PartA::EdgeDrawThread_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&rtos))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), thID(thID), rtos(rtos)
{   /* nothing */
}

EdgeDrawThread_PartA::~EdgeDrawThread_PartA(void)
{   /* nothing */
}

#line 19 "edge_draw.sc"
void EdgeDrawThread_PartA::init(void) {
    task = rtos.task_create("EDTPA");
    rtos.push_t(task);
    return ;
}


void EdgeDrawThread_PartA::main(void) {

    int i;
    unsigned char *inp; unsigned char *midp;
    int drawing_mode;

    drawing_mode = 0;



    if (drawing_mode == 0)
    {   

	midp = mid + 7220 / 2 * thID;

	for(i = 76 * 95 / 2 * thID; i < 76 * 95 / 2 * (thID + 1) + (thID + 1 == 2 && 76 * 95 % 2 != 0 ? 76 * 95 % 2 : 0); i++ )
	{   
	    rtos.time_wait(12000000);
	    if ( *midp < 8)
	    {   
		inp = image_buffer + (midp - mid) - 76 - 1;
		 *inp++  = 255;  *inp++  = 255;  *inp = 255; inp += 76 - 2;
		 *inp++  = 255;  *inp++ ;  *inp = 255; inp += 76 - 2;
		 *inp++  = 255;  *inp++  = 255;  *inp = 255;
	    }
	    midp++ ;
	}
    }
}

#line 1491 "susan_edge_detector.cc"
EdgeDrawThread_PartB::EdgeDrawThread_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&rtos))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), thID(thID), rtos(rtos)
{   /* nothing */
}

EdgeDrawThread_PartB::~EdgeDrawThread_PartB(void)
{   /* nothing */
}

#line 68 "edge_draw.sc"
void EdgeDrawThread_PartB::init(void) {
    task = rtos.task_create("EDTPB");
    rtos.push_t(task);
    return ;
}


void EdgeDrawThread_PartB::main(void) {

    int i;
    unsigned char *midp;
    int drawing_mode;

    drawing_mode = 0;


    midp = mid + 7220 / 2 * thID;

    printf("EDTPB activate check\n");



    for(i = 76 * 95 / 2 * thID; i < 76 * 95 / 2 * (thID + 1) + (thID + 1 == 2 && 76 * 95 % 2 != 0 ? 76 * 95 % 2 : 0); i++ )
    {   
	rtos.time_wait(12000000);
	if ( *midp < 8)
	     *(image_buffer + (midp - mid)) = 0;
	midp++ ;
    }
}

#line 1533 "susan_edge_detector.cc"
EdgeDraw_ReadInput::EdgeDraw_ReadInput(unsigned int _idcnt, i_uchar7220sr_receiver (&in_image), i_uchar7220sr_receiver (&in_mid), unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), in_image(in_image), in_mid(in_mid), image_buffer(image_buffer), mid(mid)
{   /* nothing */
}

EdgeDraw_ReadInput::~EdgeDraw_ReadInput(void)
{   /* nothing */
}

#line 105 "edge_draw.sc"
void EdgeDraw_ReadInput::main(void) {
    printf("edge draw image pre wait\n");
    in_image.receive( &image_buffer);
    printf("edge draw image post wait\n");
    printf("edge draw mid pre wait\n");
    in_mid.receive( &mid);
    printf("edge draw mid post wait\n");
}

#line 1553 "susan_edge_detector.cc"
EdgeDraw_WriteOutput::EdgeDraw_WriteOutput(unsigned int _idcnt, unsigned char (&image_buffer)[7220], i_uchar7220s_sender (&out_image))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), out_image(out_image)
{   /* nothing */
}

EdgeDraw_WriteOutput::~EdgeDraw_WriteOutput(void)
{   /* nothing */
}

#line 117 "edge_draw.sc"
void EdgeDraw_WriteOutput::main(void) {
    out_image.send(image_buffer);
}

#line 1568 "susan_edge_detector.cc"
EdgeDraw_PartA::EdgeDraw_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], OSAPI (&rtos))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), rtos(rtos),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    edge_draw_a_thread_0(_IDcnt, image_buffer, mid, _scc_const_port_0, rtos),
    edge_draw_a_thread_1(_IDcnt, image_buffer, mid, _scc_const_port_1, rtos)
{   /* nothing */
}

EdgeDraw_PartA::~EdgeDraw_PartA(void)
{   /* nothing */
}

#line 130 "edge_draw.sc"
void EdgeDraw_PartA::main(void) {



    printf("edge draw part A: par start\n");



    edge_draw_a_thread_0.main();
    edge_draw_a_thread_1.main();




    return ;
}

#line 1600 "susan_edge_detector.cc"
EdgeDraw_PartB::EdgeDraw_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], unsigned char (&mid)[7220], OSAPI (&rtos))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), mid(mid), rtos(rtos),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    edge_draw_b_thread_0(_IDcnt, image_buffer, mid, _scc_const_port_0, rtos),
    edge_draw_b_thread_1(_IDcnt, image_buffer, mid, _scc_const_port_1, rtos)
{   /* nothing */
}

EdgeDraw_PartB::~EdgeDraw_PartB(void)
{   /* nothing */
}

#line 156 "edge_draw.sc"
void EdgeDraw_PartB::main(void) {



    printf("edge draw part B: par start\n");



    edge_draw_b_thread_0.main();
    edge_draw_b_thread_1.main();



    return ;
}

#line 1631 "susan_edge_detector.cc"
EdgeDraw::EdgeDraw(unsigned int _idcnt, i_uchar7220sr_receiver (&in_image), i_uchar7220sr_receiver (&in_mid), i_uchar7220s_sender (&out_image), OSAPI (&rtos))
    : _specc::behavior(_idcnt), in_image(in_image), in_mid(in_mid), out_image(out_image), rtos(rtos),
    edge_draw_a(_IDcnt, image_buffer, mid, rtos),
    edge_draw_b(_IDcnt, image_buffer, mid, rtos),
    edge_draw_read_input(_IDcnt, in_image, in_mid, image_buffer, mid),
    edge_draw_write_output(_IDcnt, image_buffer, out_image)
{   /* nothing */
}

EdgeDraw::~EdgeDraw(void)
{   /* nothing */
}

#line 188 "edge_draw.sc"
void EdgeDraw::main(void) {

    { enum { _scc_state_0, _scc_state_edge_draw_read_input, _scc_state_edge_draw_a, _scc_state_edge_draw_b, _scc_state_edge_draw_write_output } _scc_next_state = _scc_state_edge_draw_read_input; do switch(_scc_next_state) {
	    case _scc_state_edge_draw_read_input: { edge_draw_read_input.main(); { _scc_next_state = _scc_state_edge_draw_a; break; } }
	    case _scc_state_edge_draw_a: { edge_draw_a.main(); { _scc_next_state = _scc_state_edge_draw_b; break; } }
	    case _scc_state_edge_draw_b: { edge_draw_b.main(); { _scc_next_state = _scc_state_edge_draw_write_output; break; } }
	    case _scc_state_edge_draw_write_output: { edge_draw_write_output.main(); { _scc_next_state = _scc_state_0; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
}

#line 1656 "susan_edge_detector.cc"
Draw::Draw(unsigned int _idcnt, i_uchar7220sr_receiver (&in_image), i_uchar7220sr_receiver (&in_mid), i_uchar7220s_sender (&out_image), OSAPI (&rtos))
    : _specc::behavior(_idcnt), in_image(in_image), in_mid(in_mid), out_image(out_image), rtos(rtos),
    edge_draw(_IDcnt, in_image, in_mid, out_image, rtos)
{   /* nothing */
}

Draw::~Draw(void)
{   /* nothing */
}

#line 207 "edge_draw.sc"
void Draw::init(void) {
    task = rtos.task_create("SDRAW");
    rtos.push_t(task);
    return ;
}

void Draw::main(void) {
    rtos.task_activate(task);
    { enum { _scc_state_0, _scc_state_edge_draw } _scc_next_state = _scc_state_edge_draw; do switch(_scc_next_state) {
	    case _scc_state_edge_draw: { edge_draw.main(); { _scc_next_state = _scc_state_edge_draw; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
    rtos.task_terminate();
}

#line 1682 "susan_edge_detector.cc"
Monitor::Monitor(unsigned int _idcnt, i_receiver (&img), i_receiver (&start_time_channel))
    : _specc::behavior(_idcnt), img(img), start_time_channel(start_time_channel)
{   /* nothing */
}

Monitor::~Monitor(void)
{   /* nothing */
}

#line 10 "monitor.sc"
void Monitor::main(void)
{   
    struct _IO_FILE *fd;
    unsigned char image_buffer[7220];
    char filename[100];
    int n;
    unsigned long long int start_time;
    for(n = 0; n < 5; n++ )
    {   
	start_time_channel.receive( &start_time, sizeof(unsigned long long int));
	sprintf(filename, "out.pgm");




	if ((fd = fopen(filename, "w")) == ((void *)0))

	{    fprintf(stderr, "Can't output image%s.\n", filename); exit(0);
	}

#line 27 "monitor.sc"
	;

	fprintf(fd, "P5\n");
	fprintf(fd, "%d %d\n", 76, 95);
	fprintf(fd, "255\n");

	img.receive(image_buffer, 7220 * sizeof(char));

	if (fwrite(image_buffer, 76 * 95, 1, fd) != 1)
	{    fprintf(stderr, "Can't write image %s.\n", filename); exit(0);
	}

#line 36 "monitor.sc"
	;

	fclose(fd);
	printf("Total process time: %llu us\n", (now() - start_time) / (1 * 1000000ull));
    }

    printf("Current time: %llu us\n", (now()) / (1 * 1000000ull));
    exit(0);
}

#line 1737 "susan_edge_detector.cc"
ReadImage::ReadImage(unsigned int _idcnt, i_receive (&start), unsigned char (&image_buffer)[7220], i_uchar7220r_sender (&out_image))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), out_image(out_image)
{   /* nothing */
}

ReadImage::~ReadImage(void)
{   /* nothing */
}

#line 15 "read_image.sc"
void ReadImage::main(void) {
    int i;
    unsigned char image_buffer_out[7220];

    while(true) {
	start.receive();
	for(i = 0; i < 7220; i++ )
	    image_buffer_out[i] = image_buffer[i];
	out_image.send(image_buffer_out);
    }
}

#line 1760 "susan_edge_detector.cc"
SetupBrightnessLutThread::SetupBrightnessLutThread(unsigned int _idcnt, unsigned char (&bp)[516], int (&thID), OSAPI (&rtos))
    : _specc::behavior(_idcnt), bp(bp), thID(thID), rtos(rtos)
{   /* nothing */
}

SetupBrightnessLutThread::~SetupBrightnessLutThread(void)
{   /* nothing */
}

#line 9 "setup_brightness_lut.sc"
void SetupBrightnessLutThread::init(void) {
    task = rtos.task_create("SLUT");
    rtos.push_t(task);
    return ;
}

void SetupBrightnessLutThread::main(void) {
    int k;
    float temp;
    int form; int thresh;

    thresh = 20;
    form = 6;




    for(k = ( -256) + 512 / 2 * thID; k < ( -256) + 512 / 2 * thID + 512 / 2 + 1; k++ ) {

	rtos.time_wait(2700);

	temp = ((float)k) / ((float)thresh);
	temp = temp * temp;
	if (form == 6)
	    temp = temp * temp * temp;
	temp = 1.000000000000000e+02 * exp( -temp);
	bp[(k + 258)] = (unsigned char)temp;
    }



    return ;
}

#line 1805 "susan_edge_detector.cc"
SetupBrightnessLut::SetupBrightnessLut(unsigned int _idcnt, unsigned char (&bp)[516], OSAPI (&rtos))
    : _specc::behavior(_idcnt), bp(bp), rtos(rtos),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    setup_brightness_thread_0(_IDcnt, bp, _scc_const_port_0, rtos),
    setup_brightness_thread_1(_IDcnt, bp, _scc_const_port_1, rtos)
{   /* nothing */
}

SetupBrightnessLut::~SetupBrightnessLut(void)
{   /* nothing */
}

#line 54 "setup_brightness_lut.sc"
void SetupBrightnessLut::main(void) {




    printf("set up brightness: par start\n");



    setup_brightness_thread_0.main();
    setup_brightness_thread_1.main();



    return ;
}

#line 1837 "susan_edge_detector.cc"
Stimulus::Stimulus(unsigned int _idcnt, i_send (&start), unsigned char (&image_buffer)[7220], i_sender (&start_time_channel))
    : _specc::behavior(_idcnt), start(start), image_buffer(image_buffer), start_time_channel(start_time_channel)
{   /* nothing */
}

Stimulus::~Stimulus(void)
{   /* nothing */
}

#line 42 "stimulus.sc"
void Stimulus::get_image(char filename[200], unsigned char *image)
{   

    struct _IO_FILE *fd;
    char header[100];
    int tmp; int x_size; int y_size;

#line 53 "stimulus.sc"
    if ((fd = fopen(filename, "r")) == ((void *)0))

    {    fprintf(stderr, "Can't input image %s.\n", filename); exit(0);
    }

#line 55 "stimulus.sc"
    ;


    header[0] = fgetc(fd);
    header[1] = fgetc(fd);
    if ( !(header[0] == 'P' && header[1] == '5'))
    {    fprintf(stderr, "Image %s does not have binary PGM header.\n", filename); exit(0);
    }

#line 61 "stimulus.sc"
    ;

    x_size = getint(fd);
    y_size = getint(fd);
    tmp = getint(fd);

    if ((x_size != 76) || (y_size != 95)) {
	fprintf(stderr, "Input picture does not match size of %dx%d\n", 76, 95);
	fclose(fd);
	exit(1);
    }

    if (fread(image, 1, 76 * 95, fd) == 0)
    {    fprintf(stderr, "Image %s is wrong size.\n", filename); exit(0);
    }

#line 74 "stimulus.sc"
    ;
    fclose(fd);
}

#line 12 "stimulus.sc"
int Stimulus::getint(struct _IO_FILE *fd)
{   
    int c; int i;
    char dummy[10000];

    c = _IO_getc(fd);
    while(1)
    {   
	if (c == '#')
	    fgets(dummy, 9000, fd);
	if (c == ( -1))
	{    fprintf(stderr, "Image %s not binary PGM.\n", "is"); exit(0);
	}

#line 23 "stimulus.sc"
	;
	if (c >= '0' && c <= '9')
	    break;
	c = _IO_getc(fd);
    }


    i = 0;
    while(1) {
	i = (i * 10) + (c - '0');
	c = _IO_getc(fd);
	if (c == ( -1)) return (i);
	if (c < '0' || c > '9') break;
    }

    return (i);
}

#line 79 "stimulus.sc"
void Stimulus::main(void)
{   
    unsigned int n;
    char filename[100];
    unsigned long long int start_time;

    sprintf(filename, "%s", "input_small.pgm");
    get_image(filename, image_buffer);
    for(n = 0; n < 5; n++ ) {
	printf("Starting process %d...\n", n + 1);
	start.send();
	start_time = now();
	start_time_channel.send( &start_time, sizeof(unsigned long long int));
	_specc::waitfor((1000));
    }
}

#line 1945 "susan_edge_detector.cc"
Susan::Susan(unsigned int _idcnt, i_uchar7220r_receiver (&in_image), i_uchar7220s_sender (&out_image), OSAPI (&rtos))
    : _specc::behavior(_idcnt), in_image(in_image), out_image(out_image), rtos(rtos),
    _scc_const_port_0(1ul),
    _scc_const_port_1(1ul),
    _scc_const_port_2(1ul),
    _scc_const_port_3(1ul),
    draw(_IDcnt, image_edge_draw, mid_edge_draw, out_image, rtos),
    edges(_IDcnt, in_image, r, mid, image_edge_draw, rtos),
    image_edge_draw(_scc_const_port_0, rtos),
    mid(_scc_const_port_1, rtos),
    mid_edge_draw(_scc_const_port_2, rtos),
    r(_scc_const_port_3, rtos),
    thin(_IDcnt, r, mid, mid_edge_draw, rtos)
{   /* nothing */
}

Susan::~Susan(void)
{   /* nothing */
}

#line 29 "susan.sc"
void Susan::init(void) {
    task = rtos.task_create("PE1");

    rtos.init(task);
    return ;
}

void Susan::main(void)
{   

    init();
    edges.init();
    thin.init();
    draw.init();

    printf("susan: par start\n");
    task = rtos.par_start();

    { _specc::fork _scc_fork_0(&edges), _scc_fork_1(&thin), _scc_fork_2(&draw); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }

    rtos.par_end(task);

    rtos.task_terminate();

    return ;
}

#line 1998 "susan_edge_detector.cc"
PE1::PE1(unsigned int _idcnt, i_uchar7220r_receiver (&in_image), i_uchar7220s_sender (&out_image), OSAPI (&rtos))
    : _specc::behavior(_idcnt), in_image(in_image), out_image(out_image), rtos(rtos),
    susan(_IDcnt, in_image, out_image, rtos)
{   /* nothing */
}

PE1::~PE1(void)
{   /* nothing */
}

#line 66 "susan.sc"
void PE1::main(void) {
    susan.main();
}

#line 2014 "susan_edge_detector.cc"
Main::Main(unsigned int _idcnt)
    : _specc::class_type(_idcnt),
    _scc_const_port_0(1000ul),
    design(_IDcnt, start, image_buffer, out_image),
    monitor(_IDcnt, out_image, start_time),
    out_image(),
    start(),
    start_time(_scc_const_port_0),
    stimulus(_IDcnt, start, image_buffer, start_time)
{   /* nothing */
}

Main::~Main(void)
{   /* nothing */
}

#line 22 "susan_edge_detector.sc"
int Main::main(void) {
    { _specc::fork _scc_fork_0(&stimulus), _scc_fork_1(&design), _scc_fork_2(&monitor); _specc::par(
	    &_scc_fork_0, 
	    &_scc_fork_1, 
	    &_scc_fork_2, ((_specc::fork*)0));
    }

    return 0;
}

#line 2042 "susan_edge_detector.cc"
Main _scc_main(_IDcnt);

int main(void)
{   
    int _scc_main_return;
    
    _specc::start();
    _scc_main_return = _scc_main.main();
    _specc::end();
    return(_scc_main_return);
}

SusanEdgesThread_PartA::SusanEdgesThread_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&bp)[516], int (&thID), OSAPI (&rtos))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), bp(bp), thID(thID), rtos(rtos)
{   /* nothing */
}

SusanEdgesThread_PartA::~SusanEdgesThread_PartA(void)
{   /* nothing */
}

#line 19 "susan_edges.sc"
void SusanEdgesThread_PartA::init(void) {
    task = rtos.task_create("SETPA");
    rtos.push_t(task);
    return ;
}

void SusanEdgesThread_PartA::main(void) {

    int max_no;
    int i; int j; int n;
    unsigned char *cp; unsigned char *p;


    max_no = 2650;




    for(i = 3 + (95 - 3 - 3) / 2 * thID; i < 3 + (95 - 3 - 3) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 3 - 3) % 2 != 0 ? (95 - 3 - 3) % 2 : 0); i++ ) {

	printf("id is %d, current i is %d, max is %d, thid is %d\n", task.id, i, 3 + (95 - 3 - 3) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 3 - 3) % 2 != 0 ? (95 - 3 - 3) % 2 : 0), thID);
	rtos.time_wait(19000000);
	for(j = 3; j < 76 - 3; j++ )
	{   
	    n = 100;
	    p = image_buffer + (i - 3) * 76 + j - 1;
	    cp = bp + 258 + image_buffer[i * 76 + j];

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 3;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 5;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 6;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 2;
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 6;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 5;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);
	    p += 76 - 3;

	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p++ );
	    n +=  *(cp -  *p);

	    if (n <= max_no)
		r[i * 76 + j] = max_no - n;
	}
    }


    printf("id is %d, terminate!!\n", task.id);
}

#line 2152 "susan_edge_detector.cc"
SusanEdgesThread_PartB::SusanEdgesThread_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&bp)[516], int (&thID), OSAPI (&rtos))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), mid(mid), bp(bp), thID(thID), rtos(rtos)
{   /* nothing */
}

SusanEdgesThread_PartB::~SusanEdgesThread_PartB(void)
{   /* nothing */
}

#line 116 "susan_edges.sc"
void SusanEdgesThread_PartB::init(void) {
    task = rtos.task_create("SETPB");
    rtos.push_t(task);
    return ;
}


void SusanEdgesThread_PartB::main(void) {

    int max_no;
    float z;
    int a; int b; int do_symmetry; int i; int j; int m; int n; int w; int x; int y;
    unsigned char c; unsigned char *cp; unsigned char *p;



    max_no = 2650;

#line 138 "susan_edges.sc"
    for(i = 4 + (95 - 4 - 4) / 2 * thID; i < 4 + (95 - 4 - 4) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 4 - 4) % 2 != 0 ? (95 - 4 - 4) % 2 : 0); i++ ) {
	rtos.time_wait(20000000);
	for(j = 4; j < 76 - 4; j++ )
	{   
	    if (r[i * 76 + j] > 0)
	    {   
		m = r[i * 76 + j];
		n = max_no - m;
		cp = bp + 258 + image_buffer[i * 76 + j];

		if (n > 600)
		{   
		    p = image_buffer + (i - 3) * 76 + j - 1;
		    x = 0; y = 0;

		    c =  *(cp -  *p++ ); x -= c; y -= 3 * c;
		    c =  *(cp -  *p++ ); y -= 3 * c;
		    c =  *(cp -  *p); x += c; y -= 3 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x -= 2 * c; y -= 2 * c;
		    c =  *(cp -  *p++ ); x -= c; y -= 2 * c;
		    c =  *(cp -  *p++ ); y -= 2 * c;
		    c =  *(cp -  *p++ ); x += c; y -= 2 * c;
		    c =  *(cp -  *p); x += 2 * c; y -= 2 * c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x -= 3 * c; y -= c;
		    c =  *(cp -  *p++ ); x -= 2 * c; y -= c;
		    c =  *(cp -  *p++ ); x -= c; y -= c;
		    c =  *(cp -  *p++ ); y -= c;
		    c =  *(cp -  *p++ ); x += c; y -= c;
		    c =  *(cp -  *p++ ); x += 2 * c; y -= c;
		    c =  *(cp -  *p); x += 3 * c; y -= c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x -= 3 * c;
		    c =  *(cp -  *p++ ); x -= 2 * c;
		    c =  *(cp -  *p); x -= c;
		    p += 2;
		    c =  *(cp -  *p++ ); x += c;
		    c =  *(cp -  *p++ ); x += 2 * c;
		    c =  *(cp -  *p); x += 3 * c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x -= 3 * c; y += c;
		    c =  *(cp -  *p++ ); x -= 2 * c; y += c;
		    c =  *(cp -  *p++ ); x -= c; y += c;
		    c =  *(cp -  *p++ ); y += c;
		    c =  *(cp -  *p++ ); x += c; y += c;
		    c =  *(cp -  *p++ ); x += 2 * c; y += c;
		    c =  *(cp -  *p); x += 3 * c; y += c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x -= 2 * c; y += 2 * c;
		    c =  *(cp -  *p++ ); x -= c; y += 2 * c;
		    c =  *(cp -  *p++ ); y += 2 * c;
		    c =  *(cp -  *p++ ); x += c; y += 2 * c;
		    c =  *(cp -  *p); x += 2 * c; y += 2 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x -= c; y += 3 * c;
		    c =  *(cp -  *p++ ); y += 3 * c;
		    c =  *(cp -  *p); x += c; y += 3 * c;

		    z = sqrt((float)((x * x) + (y * y)));
		    if (z > (9.000000000000000e-01 * (float)n))
		    {   
			do_symmetry = 0;
			if (x == 0)
			    z = 1.000000000000000e+06;
			else 
			    z = ((float)y) / ((float)x);
			if (z < 0) { z =  -z; w =  -1;
			}
			else 

#line 212 "susan_edges.sc"
			    w = 1;
			if (z < 5.000000000000000e-01) { a = 0; b = 1;
			}
			else 

#line 214 "susan_edges.sc"
			{    if (z > 2.000000000000000e+00) { a = 1; b = 0;
			    }
			    else 

#line 215 "susan_edges.sc"
			    {    if (w > 0) { a = 1; b = 1;
				}
				else 

#line 216 "susan_edges.sc"
				{    a =  -1; b = 1;
				}
			    }
			}

#line 217 "susan_edges.sc"
			if ((m > r[(i + a) * 76 + j + b]) && (m >= r[(i - a) * 76 + j - b]) && 
			    (m > r[(i + (2 * a)) * 76 + j + (2 * b)]) && (m >= r[(i - (2 * a)) * 76 + j - (2 * b)]))
			    mid[i * 76 + j] = 1;
		    }
		    else 
			do_symmetry = 1;
		}
		else 
		    do_symmetry = 1;

		if (do_symmetry == 1)
		{   
		    p = image_buffer + (i - 3) * 76 + j - 1;
		    x = 0; y = 0; w = 0;

#line 236 "susan_edges.sc"
		    c =  *(cp -  *p++ ); x += c; y += 9 * c; w += 3 * c;
		    c =  *(cp -  *p++ ); y += 9 * c;
		    c =  *(cp -  *p); x += c; y += 9 * c; w -= 3 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x += 4 * c; y += 4 * c; w += 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w += 2 * c;
		    c =  *(cp -  *p++ ); y += 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w -= 2 * c;
		    c =  *(cp -  *p); x += 4 * c; y += 4 * c; w -= 4 * c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x += 9 * c; y += c; w += 3 * c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w += 2 * c;
		    c =  *(cp -  *p++ ); x += c; y += c; w += c;
		    c =  *(cp -  *p++ ); y += c;
		    c =  *(cp -  *p++ ); x += c; y += c; w -= c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w -= 2 * c;
		    c =  *(cp -  *p); x += 9 * c; y += c; w -= 3 * c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x += 9 * c;
		    c =  *(cp -  *p++ ); x += 4 * c;
		    c =  *(cp -  *p); x += c;
		    p += 2;
		    c =  *(cp -  *p++ ); x += c;
		    c =  *(cp -  *p++ ); x += 4 * c;
		    c =  *(cp -  *p); x += 9 * c;
		    p += 76 - 6;

		    c =  *(cp -  *p++ ); x += 9 * c; y += c; w -= 3 * c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w -= 2 * c;
		    c =  *(cp -  *p++ ); x += c; y += c; w -= c;
		    c =  *(cp -  *p++ ); y += c;
		    c =  *(cp -  *p++ ); x += c; y += c; w += c;
		    c =  *(cp -  *p++ ); x += 4 * c; y += c; w += 2 * c;
		    c =  *(cp -  *p); x += 9 * c; y += c; w += 3 * c;
		    p += 76 - 5;

		    c =  *(cp -  *p++ ); x += 4 * c; y += 4 * c; w -= 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w -= 2 * c;
		    c =  *(cp -  *p++ ); y += 4 * c;
		    c =  *(cp -  *p++ ); x += c; y += 4 * c; w += 2 * c;
		    c =  *(cp -  *p); x += 4 * c; y += 4 * c; w += 4 * c;
		    p += 76 - 3;

		    c =  *(cp -  *p++ ); x += c; y += 9 * c; w -= 3 * c;
		    c =  *(cp -  *p++ ); y += 9 * c;
		    c =  *(cp -  *p); x += c; y += 9 * c; w += 3 * c;

		    if (y == 0)
			z = 1.000000000000000e+06;
		    else 
			z = ((float)x) / ((float)y);
		    if (z < 5.000000000000000e-01) { a = 0; b = 1;
		    }
		    else 

#line 291 "susan_edges.sc"
		    {    if (z > 2.000000000000000e+00) { a = 1; b = 0;
			}
			else 

#line 292 "susan_edges.sc"
			{    if (w > 0) { a =  -1; b = 1;
			    }
			    else 

#line 293 "susan_edges.sc"
			    {    a = 1; b = 1;
			    }
			}
		    }

#line 294 "susan_edges.sc"
		    if ((m > r[(i + a) * 76 + j + b]) && (m >= r[(i - a) * 76 + j - b]) && 
			(m > r[(i + (2 * a)) * 76 + j + (2 * b)]) && (m >= r[(i - (2 * a)) * 76 + j - (2 * b)]))
			mid[i * 76 + j] = 2;
		}
	    }
	}
    }
}

#line 2382 "susan_edge_detector.cc"
SusanEdges_ReadInput::SusanEdges_ReadInput(unsigned int _idcnt, i_uchar7220r_receiver (&in_image), unsigned char (&in_image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), in_image(in_image), in_image_buffer(in_image_buffer), r(r), mid(mid)
{   /* nothing */
}

SusanEdges_ReadInput::~SusanEdges_ReadInput(void)
{   /* nothing */
}

#line 311 "susan_edges.sc"
void SusanEdges_ReadInput::main(void) {
    printf("susan edges read input pre wait\n");
    in_image.receive( &in_image_buffer);
    printf("susan edges read input post wait\n");

    memset(mid, 100, 76 * 95);
    memset(r, 0, 76 * 95 * sizeof(int));
}

#line 2402 "susan_edge_detector.cc"
SusanEdges_WriteOutput::SusanEdges_WriteOutput(unsigned int _idcnt, i_int7220sr_sender (&out_r), i_uchar7220sr_sender (&out_mid), i_uchar7220sr_sender (&out_image), int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&out_image_buffer)[7220])
    : _specc::behavior(_idcnt), out_r(out_r), out_mid(out_mid), out_image(out_image), r(r), mid(mid), out_image_buffer(out_image_buffer)
{   /* nothing */
}

SusanEdges_WriteOutput::~SusanEdges_WriteOutput(void)
{   /* nothing */
}

#line 326 "susan_edges.sc"
void SusanEdges_WriteOutput::main(void) {
    out_r.send(r);
    out_mid.send(mid);
    out_image.send(out_image_buffer);
}

#line 2419 "susan_edge_detector.cc"
SusanEdges_PartA::SusanEdges_PartA(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&bp)[516], OSAPI (&rtos))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), bp(bp), rtos(rtos),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    susan_edges_a_thread_0(_IDcnt, image_buffer, r, bp, _scc_const_port_0, rtos),
    susan_edges_a_thread_1(_IDcnt, image_buffer, r, bp, _scc_const_port_1, rtos)
{   /* nothing */
}

SusanEdges_PartA::~SusanEdges_PartA(void)
{   /* nothing */
}

#line 341 "susan_edges.sc"
void SusanEdges_PartA::main(void) {




    printf("susan edges part A: par start\n");



    susan_edges_a_thread_0.main();
    susan_edges_a_thread_1.main();



    return ;
}

#line 2451 "susan_edge_detector.cc"
SusanEdges_PartB::SusanEdges_PartB(unsigned int _idcnt, unsigned char (&image_buffer)[7220], int (&r)[7220], unsigned char (&mid)[7220], unsigned char (&bp)[516], OSAPI (&rtos))
    : _specc::behavior(_idcnt), image_buffer(image_buffer), r(r), mid(mid), bp(bp), rtos(rtos),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    susan_edges_b_thread_0(_IDcnt, image_buffer, r, mid, bp, _scc_const_port_0, rtos),
    susan_edges_b_thread_1(_IDcnt, image_buffer, r, mid, bp, _scc_const_port_1, rtos)
{   /* nothing */
}

SusanEdges_PartB::~SusanEdges_PartB(void)
{   /* nothing */
}

#line 367 "susan_edges.sc"
void SusanEdges_PartB::main(void) {




    printf("susan edges part B: par start\n");



    susan_edges_b_thread_0.main();
    susan_edges_b_thread_1.main();



    return ;
}

#line 2483 "susan_edge_detector.cc"
SusanEdges::SusanEdges(unsigned int _idcnt, i_uchar7220r_receiver (&in_image), i_int7220sr_sender (&out_r), i_uchar7220sr_sender (&out_mid), unsigned char (&bp)[516], i_uchar7220sr_sender (&out_image), OSAPI (&rtos))
    : _specc::behavior(_idcnt), in_image(in_image), out_r(out_r), out_mid(out_mid), bp(bp), out_image(out_image), rtos(rtos),
    susan_edges_a(_IDcnt, image_buffer, r, bp, rtos),
    susan_edges_b(_IDcnt, image_buffer, r, mid, bp, rtos),
    susan_edges_read_input(_IDcnt, in_image, image_buffer, r, mid),
    susan_edges_write_output(_IDcnt, out_r, out_mid, out_image, r, mid, image_buffer)
{   /* nothing */
}

SusanEdges::~SusanEdges(void)
{   /* nothing */
}

#line 398 "susan_edges.sc"
void SusanEdges::main(void) {

    { enum { _scc_state_0, _scc_state_susan_edges_read_input, _scc_state_susan_edges_a, _scc_state_susan_edges_b, _scc_state_susan_edges_write_output } _scc_next_state = _scc_state_susan_edges_read_input; do switch(_scc_next_state) {
	    case _scc_state_susan_edges_read_input: { susan_edges_read_input.main(); { _scc_next_state = _scc_state_susan_edges_a; break; } }
	    case _scc_state_susan_edges_a: { susan_edges_a.main(); { _scc_next_state = _scc_state_susan_edges_b; break; } }
	    case _scc_state_susan_edges_b: { susan_edges_b.main(); { _scc_next_state = _scc_state_susan_edges_write_output; break; } }
	    case _scc_state_susan_edges_write_output: { susan_edges_write_output.main(); { _scc_next_state = _scc_state_0; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }
}

#line 2508 "susan_edge_detector.cc"
SusanThinThread::SusanThinThread(unsigned int _idcnt, int (&r)[7220], unsigned char (&mid)[7220], int (&thID), OSAPI (&rtos))
    : _specc::behavior(_idcnt), r(r), mid(mid), thID(thID), rtos(rtos)
{   /* nothing */
}

SusanThinThread::~SusanThinThread(void)
{   /* nothing */
}

#line 18 "susan_thin.sc"
void SusanThinThread::init(void) {
    task = rtos.task_create("STT");
    rtos.push_t(task);
    return ;
}

void SusanThinThread::main(void) {
    int centre; int l[9];
    int b01; int b10; int b12; int b21;
    int p1; int p2; int p3; int p4;
    int b00; int b02; int b20; int b22;
    int a; int b; int i; int j; int m; int n; int x; int y;
    unsigned char *mp;



    for(i = 4 + (95 - 4 - 4) / 2 * thID; i < 4 + (95 - 4 - 4) / 2 * (thID + 1) + (thID + 1 == 2 && (95 - 4 - 4) % 2 != 0 ? (95 - 4 - 4) % 2 : 0); i++ ) {

	rtos.time_wait(6400000);

	for(j = 4; j < 76 - 4; j++ )
	    if (mid[i * 76 + j] < 8)
	    {   
		centre = r[i * 76 + j];


		mp = mid + (i - 1) * 76 + j - 1;

		n = ( *mp < 8) + 
		( *(mp + 1) < 8) + 
		( *(mp + 2) < 8) + 
		( *(mp + 76) < 8) + 
		( *(mp + 76 + 2) < 8) + 
		( *(mp + 76 + 76) < 8) + 
		( *(mp + 76 + 76 + 1) < 8) + 
		( *(mp + 76 + 76 + 2) < 8);



		if (n == 0)
		    mid[i * 76 + j] = 100;




		if ((n == 1) && (mid[i * 76 + j] < 6))
		{   

#line 71 "susan_thin.sc"
		    l[0] = r[(i - 1) * 76 + j - 1]; l[1] = r[(i - 1) * 76 + j]; l[2] = r[(i - 1) * 76 + j + 1];
		    l[3] = r[(i) * 76 + j - 1]; l[4] = 0; l[5] = r[(i) * 76 + j + 1];
		    l[6] = r[(i + 1) * 76 + j - 1]; l[7] = r[(i + 1) * 76 + j]; l[8] = r[(i + 1) * 76 + j + 1];

		    if (mid[(i - 1) * 76 + j - 1] < 8) { l[0] = 0; l[1] = 0; l[3] = 0; l[2] *= 2;
			l[6] *= 2; l[5] *= 3; l[7] *= 3; l[8] *= 4;
		    }
		    else 

#line 77 "susan_thin.sc"
		    {    if (mid[(i - 1) * 76 + j] < 8) { l[1] = 0; l[0] = 0; l[2] = 0; l[3] *= 2;
			    l[5] *= 2; l[6] *= 3; l[8] *= 3; l[7] *= 4;
			}
			else 

#line 79 "susan_thin.sc"
			{    if (mid[(i - 1) * 76 + j + 1] < 8) { l[2] = 0; l[1] = 0; l[5] = 0; l[0] *= 2;
				l[8] *= 2; l[3] *= 3; l[7] *= 3; l[6] *= 4;
			    }
			    else 

#line 81 "susan_thin.sc"
			    {    if (mid[(i) * 76 + j - 1] < 8) { l[3] = 0; l[0] = 0; l[6] = 0; l[1] *= 2;
				    l[7] *= 2; l[2] *= 3; l[8] *= 3; l[5] *= 4;
				}
				else 

#line 83 "susan_thin.sc"
				{    if (mid[(i) * 76 + j + 1] < 8) { l[5] = 0; l[2] = 0; l[8] = 0; l[1] *= 2;
					l[7] *= 2; l[0] *= 3; l[6] *= 3; l[3] *= 4;
				    }
				    else 

#line 85 "susan_thin.sc"
				    {    if (mid[(i + 1) * 76 + j - 1] < 8) { l[6] = 0; l[3] = 0; l[7] = 0; l[0] *= 2;
					    l[8] *= 2; l[1] *= 3; l[5] *= 3; l[2] *= 4;
					}
					else 

#line 87 "susan_thin.sc"
					{    if (mid[(i + 1) * 76 + j] < 8) { l[7] = 0; l[6] = 0; l[8] = 0; l[3] *= 2;
						l[5] *= 2; l[0] *= 3; l[2] *= 3; l[1] *= 4;
					    }
					    else 

#line 89 "susan_thin.sc"
					    {    if (mid[(i + 1) * 76 + j + 1] < 8) { l[8] = 0; l[5] = 0; l[7] = 0; l[6] *= 2;
						    l[2] *= 2; l[1] *= 3; l[3] *= 3; l[0] *= 4;
						}
					    }
					}
				    }
				}
			    }
			}
		    }

#line 92 "susan_thin.sc"
		    m = 0;
		    for(y = 0; y < 3; y++ )
			for(x = 0; x < 3; x++ )
			    if (l[y + y + y + x] > m) { m = l[y + y + y + x]; a = y; b = x;
			    }
		    if (m > 0)
		    {   
			if (mid[i * 76 + j] < 4)
			    mid[(i + a - 1) * 76 + j + b - 1] = 4;
			else 
			    mid[(i + a - 1) * 76 + j + b - 1] = mid[i * 76 + j] + 1;
			if ((a + a + b) < 3)
			{   
			    i += a - 1;
			    j += b - 2;
			    if (i < 4) i = 4;
			    if (j < 4) j = 4;
			}
		    }
		}

		if (n == 2)
		{   

		    b00 = mid[(i - 1) * 76 + j - 1] < 8;
		    b02 = mid[(i - 1) * 76 + j + 1] < 8;
		    b20 = mid[(i + 1) * 76 + j - 1] < 8;
		    b22 = mid[(i + 1) * 76 + j + 1] < 8;
		    if (((b00 + b02 + b20 + b22) == 2) && ((b00 | b22) & (b02 | b20)))
		    {   



			if (b00)
			{   
			    if (b02) { x = 0; y =  -1;
			    }
			    else 

#line 128 "susan_thin.sc"
			    {    x =  -1; y = 0;
			    }
			}
			else  {
			    if (b02) { x = 1; y = 0;
			    }
			    else 

#line 133 "susan_thin.sc"
			    {    x = 0; y = 1;
			    }
			} if (((float)r[(i + y) * 76 + j + x] / (float)centre) > 7.000000000000000e-01)
			{   
			    if (((x == 0) && (mid[(i + (2 * y)) * 76 + j] > 7) && (mid[(i + (2 * y)) * 76 + j - 1] > 7) && (mid[(i + (2 * y)) * 76 + j + 1] > 7)) || 
				((y == 0) && (mid[(i) * 76 + j + (2 * x)] > 7) && (mid[(i + 1) * 76 + j + (2 * x)] > 7) && (mid[(i - 1) * 76 + j + (2 * x)] > 7)))
			    {   
				mid[(i) * 76 + j] = 100;
				mid[(i + y) * 76 + j + x] = 3;
			    }
			}
		    }
		    else 
		    {   
			b01 = mid[(i - 1) * 76 + j] < 8;
			b12 = mid[(i) * 76 + j + 1] < 8;
			b21 = mid[(i + 1) * 76 + j] < 8;
			b10 = mid[(i) * 76 + j - 1] < 8;

#line 175 "susan_thin.sc"
			if (((b01 + b12 + b21 + b10) == 2) && ((b10 | b12) & (b01 | b21)) && 
			    ((b01 & ((mid[(i - 2) * 76 + j - 1] < 8) | (mid[(i - 2) * 76 + j + 1] < 8))) | (b10 & ((mid[(i - 1) * 76 + j - 2] < 8) | (mid[(i + 1) * 76 + j - 2] < 8))) | 
				(b12 & ((mid[(i - 1) * 76 + j + 2] < 8) | (mid[(i + 1) * 76 + j + 2] < 8))) | (b21 & ((mid[(i + 2) * 76 + j - 1] < 8) | (mid[(i + 2) * 76 + j + 1] < 8)))))
			{   



			    mid[(i) * 76 + j] = 100;
			    i-- ;
			    j -= 2;
			    if (i < 4) i = 4;
			    if (j < 4) j = 4;
			}
		    }
		}

		if (n > 2)
		{   
		    b01 = mid[(i - 1) * 76 + j] < 8;
		    b12 = mid[(i) * 76 + j + 1] < 8;
		    b21 = mid[(i + 1) * 76 + j] < 8;
		    b10 = mid[(i) * 76 + j - 1] < 8;
		    if ((b01 + b12 + b21 + b10) > 1)
		    {   
			b00 = mid[(i - 1) * 76 + j - 1] < 8;
			b02 = mid[(i - 1) * 76 + j + 1] < 8;
			b20 = mid[(i + 1) * 76 + j - 1] < 8;
			b22 = mid[(i + 1) * 76 + j + 1] < 8;
			p1 = b00 | b01;
			p2 = b02 | b12;
			p3 = b22 | b21;
			p4 = b20 | b10;

			if (((p1 + p2 + p3 + p4) - ((b01 & p2) + (b12 & p3) + (b21 & p4) + (b10 & p1))) < 2)
			{   
			    mid[(i) * 76 + j] = 100;
			    i-- ;
			    j -= 2;
			    if (i < 4) i = 4;
			    if (j < 4) j = 4;
			}
		    }
		}
	    }
    }
}

#line 2742 "susan_edge_detector.cc"
SusanThin_ReadInput::SusanThin_ReadInput(unsigned int _idcnt, i_int7220sr_receiver (&in_r), i_uchar7220sr_receiver (&in_mid), int (&r)[7220], unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), in_r(in_r), in_mid(in_mid), r(r), mid(mid)
{   /* nothing */
}

SusanThin_ReadInput::~SusanThin_ReadInput(void)
{   /* nothing */
}

#line 231 "susan_thin.sc"
void SusanThin_ReadInput::main(void) {
    printf("susan thin r pre wait\n");
    in_r.receive( &r);
    printf("susan thin r post wait\n");
    printf("susan thin mid pre wait\n");
    in_mid.receive( &mid);
    printf("susan thin mid post wait\n");
}

#line 2762 "susan_edge_detector.cc"
SusanThin_WriteOutput::SusanThin_WriteOutput(unsigned int _idcnt, i_uchar7220sr_sender (&out_mid), unsigned char (&mid)[7220])
    : _specc::behavior(_idcnt), out_mid(out_mid), mid(mid)
{   /* nothing */
}

SusanThin_WriteOutput::~SusanThin_WriteOutput(void)
{   /* nothing */
}

#line 243 "susan_thin.sc"
void SusanThin_WriteOutput::main(void) {
    out_mid.send(mid);
}

#line 2777 "susan_edge_detector.cc"
SusanThin::SusanThin(unsigned int _idcnt, int (&r)[7220], unsigned char (&mid)[7220], OSAPI (&rtos))
    : _specc::behavior(_idcnt), r(r), mid(mid), rtos(rtos),
    _scc_const_port_0(0),
    _scc_const_port_1(1),
    susan_thin_thread_0(_IDcnt, r, mid, _scc_const_port_0, rtos),
    susan_thin_thread_1(_IDcnt, r, mid, _scc_const_port_1, rtos)
{   /* nothing */
}

SusanThin::~SusanThin(void)
{   /* nothing */
}

#line 256 "susan_thin.sc"
void SusanThin::main(void) {




    printf("susan thin: par start\n");



    susan_thin_thread_0.main();
    susan_thin_thread_1.main();




    return ;
}

#line 2810 "susan_edge_detector.cc"
Thin::Thin(unsigned int _idcnt, i_int7220sr_receiver (&in_r), i_uchar7220sr_receiver (&in_mid), i_uchar7220sr_sender (&out_mid), OSAPI (&rtos))
    : _specc::behavior(_idcnt), in_r(in_r), in_mid(in_mid), out_mid(out_mid), rtos(rtos),
    susan_thin(_IDcnt, r, mid, rtos),
    susan_thin_read_input(_IDcnt, in_r, in_mid, r, mid),
    susan_thin_write_output(_IDcnt, out_mid, mid)
{   /* nothing */
}

Thin::~Thin(void)
{   /* nothing */
}

#line 289 "susan_thin.sc"
void Thin::init(void) {
    task = rtos.task_create("STHIN");
    rtos.push_t(task);
    return ;
}

void Thin::main(void) {

    rtos.task_activate(task);

    { enum { _scc_state_0, _scc_state_susan_thin_read_input, _scc_state_susan_thin, _scc_state_susan_thin_write_output } _scc_next_state = _scc_state_susan_thin_read_input; do switch(_scc_next_state) {
	    case _scc_state_susan_thin_read_input: { susan_thin_read_input.main(); { _scc_next_state = _scc_state_susan_thin; break; } }
	    case _scc_state_susan_thin: { susan_thin.main(); { _scc_next_state = _scc_state_susan_thin_write_output; break; } }
	    case _scc_state_susan_thin_write_output: { susan_thin_write_output.main(); { _scc_next_state = _scc_state_susan_thin_read_input; break; } } case _scc_state_0: { _scc_next_state = _scc_state_0; break; } } while(_scc_next_state != _scc_state_0);
    }

    rtos.task_terminate();
}

#line 2843 "susan_edge_detector.cc"
WriteImage::WriteImage(unsigned int _idcnt, i_uchar7220s_receiver (&in_image), i_sender (&out_image))
    : _specc::behavior(_idcnt), in_image(in_image), out_image(out_image)
{   /* nothing */
}

WriteImage::~WriteImage(void)
{   /* nothing */
}

#line 15 "write_image.sc"
void WriteImage::main(void) {

    unsigned char image_buffer[7220];

    while(true) {
	in_image.receive( &image_buffer);
	out_image.send(image_buffer, sizeof (image_buffer));
    }
}

#line 2864 "susan_edge_detector.cc"
void _scc_bit4_err_handle(
    const _bit4& bit4vec)
{   
    char temp_bits[1024], *p;
    p=bit2str(2,&temp_bits[1023], bit4vec);
    _specc::abort(
	"ERROR:\t Casting a bit4 vector failed \n"
	"Bit4 vector contains X/Z values %s\n"
	"Simulation aborted.\n", p);
	
}

//////////////////////////////////////////////////////////////////////
// End of file susan_edge_detector.cc
//////////////////////////////////////////////////////////////////////
