DEFINE_I_TYPED_SENDER(r, int)
DEFINE_I_TYPED_RECEIVER(r, int)
DEFINE_I_TYPED_DOUBLE_HANDSHAKE(r, int)
DEFINE_I_TYPED_QUEUE(r, int)

DEFINE_I_TYPED_SENDER(mid, unsigned char)
DEFINE_I_TYPED_RECEIVER(mid, unsigned char)
DEFINE_I_TYPED_DOUBLE_HANDSHAKE(mid, unsigned char)
DEFINE_I_TYPED_QUEUE(mid, unsigned char)


DEFINE_I_TYPED_SENDER(in, unsigned char)
DEFINE_I_TYPED_RECEIVER(in, unsigned char)
DEFINE_I_TYPED_DOUBLE_HANDSHAKE(in, unsigned char)
DEFINE_I_TYPED_QUEUE(in, unsigned char)
